<template>
  <v-app
    :theme="isDark ? 'dark' : 'light'"
    :class="isDark ? 'tempDiv-dark' : 'tempDiv'"
  >
    <v-container fluid>
      <v-row>
        <v-col cols="12" md="2" sm="0" class="nav sm:mb-5">
          <Navigation />
        </v-col>
        <v-col
          cols="12"
          md="12"
          lg="10"
          style="min-width: 70%; max-width: 100%"
          class="main"
        >
          <div class="pt-4 upperDiv">
            <h1 class="text-3xl font-medium title">Rubric Forms</h1>
            <p class="text-base titleDes font-light">
              Here you can find all the rubric forms related to evaluation and
              grading.
            </p>
          </div>

          <div class="lowerDiv pt-10 lg:w-4/5">
            <v-form
              v-if="isAdmin || isCoordinator"
              ref="formsForm"
              v-model="valid"
            >
              <v-card
                class="vCard"
                variant="elevated"
                outlined
                :color="isDark ? 'white' : 'grey-lighten-5'"
                style="border-radius: 10px"
              >
                <v-card-title class="text-2xl font-medium title">
                  Upload Forms
                </v-card-title>
                <v-card-text>
                  <p class="text-base titleDes font-light mb-4">
                    Please upload the forms here for students to download.
                  </p>
                  <v-file-input
                    v-model="FormFiles"
                    multiple
                    variant="outlined"
                    chips
                    clearable
                    label="Files"
                    :rules="[() => !!FormFiles.length || 'File is required']"
                    show-size
                    hint="can upload multiple files"
                    counter
                  ></v-file-input>
                </v-card-text>
                <v-card-actions>
                  <v-spacer></v-spacer>
                  <v-btn
                    color="indigo"
                    variant="elevated"
                    size="large"
                    :disabled="!valid"
                    class="mt-5"
                    @click="uploadFiles"
                    ><v-icon class="mr-2"><upload /></v-icon>Upload File</v-btn
                  >
                </v-card-actions>
              </v-card>
            </v-form>
            <p
              v-if="!filesInfo.length && !isLoading"
              class="text-orange-400 text-lg titleDes my-4"
            >
              No Files uploaded yet
            </p>
            <v-row v-show="!isLoading" class="pt-5">
              <v-col v-for="file in filesInfo" :key="file.id" cols="12">
                <v-card
                  class="pa-3 rounded-lg"
                  variant="tonal"
                  :color="isDark ? 'blue-grey-lighten-2' : 'blue-grey-darken-4'"
                >
                  <v-card-subtitle
                    >{{ file.createdAt }}
                    <v-btn
                      v-if="isAdmin || isCoordinator"
                      color="error"
                      size="small"
                      variant="text"
                      class="text-red-400 ml-4 title"
                      text="Delete"
                      @click="deleteFile(file.id, file.autogeneratedName)"
                    ></v-btn
                  ></v-card-subtitle>
                  <v-card-text>
                    <div
                      class="flex title justify-between flex-col md:flex-row"
                    >
                      <h1
                        class="text-base text-ellipsis max-w-md whitespace-nowrap overflow-hidden"
                      >
                        {{ file.originalName }}
                      </h1>
                      <a
                        :href="`${apiUrl}/files/${file.autogeneratedName}`"
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        <v-icon size="large" :icon="forms"></v-icon>
                        <span
                          class="text-base underline pl-2 text-blue-800 dark:text-blue-400"
                          >{{ file.autogeneratedName }}</span
                        >
                      </a>
                    </div>
                  </v-card-text>
                </v-card>
              </v-col>
            </v-row>
            <v-skeleton-loader
              v-if="isLoading"
              class="mw-auto mt-5 py-6 rounded-lg"
              type="heading"
            ></v-skeleton-loader>
          </div>
        </v-col>
      </v-row>
    </v-container>

    <v-snackbar
      :timeout="2000"
      color="indigo"
      variant="elevated"
      v-model="snackbar"
    >
      {{ snackbarMessage }}

      <template v-slot:actions>
        <v-btn color="white" variant="transparent" @click="snackbar = false">
          X
        </v-btn>
      </template>
    </v-snackbar>
  </v-app>
</template>

<script setup>
import upload from "@/assets/icons/upload.vue";
import forms from "@/assets/icons/forms.vue";
import Navigation from "../navigation.vue";
import { useDark } from "@vueuse/core";
import { ref, onMounted } from "vue";
import axios from "axios";
import { useJwt } from "@vueuse/integrations/useJwt";

// Constants
const isDark = useDark();
const apiUrl = import.meta.env.VITE_API_URL;
const token = ref(localStorage.getItem("access_token"));
const { header, payload } = useJwt(token);
const isAdmin = payload.value.isAdmin;
const isCoordinator = payload.value.isCoordinator;
const snackbar = ref(false);
const snackbarMessage = ref("");
const errorMessage = ref("");
const FormFiles = ref([]);
const valid = ref(true);
const formsForm = ref(null);
const filesInfo = ref([]);
const isLoading = ref(false);

const uploadFiles = async () => {
  const token = localStorage.getItem("access_token");
  const formData = new FormData();

  for (let i = 0; i < FormFiles.value.length; i++) {
    formData.append("files", FormFiles.value[i]);
  }
  formData.append("submissionType", "rubricFiles");
  try {
    const response = await axios.post(`${apiUrl}/upload`, formData, {
      headers: {
        Authorization: token,
        "Content-Type": "multipart/form-data",
      },
    });
    if (response.status === 200) {
      snackbarMessage.value = "File(s) uploaded successfully!";
      snackbar.value = true;
      filesInfo.value.push(
        ...response.data.fileSubmissionData.map((file) => ({
          ...file,
          createdAt: formatDate(file.createdAt),
        }))
      );
    }
  } catch (error) {
    errorMessage.value = error.response.data.message;
    snackbarMessage.value = errorMessage.value;
    snackbar.value = true;
  }
};

onMounted(async () => {
  isLoading.value = true;
  try {
    const responseMain = await axios.get(`${apiUrl}/api/files/rubricFiles`, {
      headers: {
        "Content-Type": "application/json",
      },
    });
    if (responseMain.data.length === 0) {
      filesInfo.value = [];
    } else {
      filesInfo.value = responseMain.data.map((file) => {
        return {
          ...file,
          originalName: file.originalName.split(".").slice(0, -1).join("."),
          createdAt: formatDate(file.createdAt),
        };
      });
    }
  } catch (error) {
    if (error.response && error.response === 404) {
      errorMessage.value = error.response.data.message;
      snackbarMessage.value = errorMessage.value;
      snackbar.value = true;
    }
  }
  isLoading.value = false;
});

const deleteFile = async (id, autogeneratedName) => {
  const token = localStorage.getItem("access_token");
  try {
    const response = await axios.delete(`${apiUrl}/api/deleteFile/${id}`, {
      headers: {
        Authorization: token,
      },
      data: {
        collectionName: "rubricFiles",
        fileName: autogeneratedName,
      },
    });
    if (response.status === 200) {
      snackbarMessage.value = "File deleted successfully!";
      snackbar.value = true;
      filesInfo.value = filesInfo.value.filter(
        (file) => file.autogeneratedName !== autogeneratedName
      );
      errorMessage.value = "";
    }
  } catch (error) {
    if ((error.response && error.response === 404) || error.response === 500) {
      errorMessage.value = error.response.data.message;
    }
    errorMessage.value =
      error.response.data.error || "An error occurred while deleting the file";
  }
};

const formatDate = (timestamp) => {
  const date = new Date(timestamp._seconds * 1000); // Convert seconds to milliseconds
  return date.toLocaleString("en-UK", {
    year: "numeric",
    month: "numeric",
    day: "numeric",
    hour: "numeric",
    minute: "numeric",
    hour12: true,
  });
};
</script>

<style lang="scss" scoped>
@media screen and (max-width: 1488px) {
  .nav {
    max-width: 1%;
  }
  .main {
    min-width: 100% !important;
  }
}
@media screen and (max-width: 639px) {
  .main {
    margin-top: 20px !important;
  }
}

.title,
.titleDes {
  font-family: "DM Sans", sans-serif;
}
.tempDiv {
  background-color: #fdfefb !important;
}
.tempDiv-dark {
  background-color: #0d0d0d !important;
}
.vCard:nth-child(1) {
  margin-top: 0px !important;
}
</style>
