const FileSubmission = require("../../models/generalModels/fileSubmissionModel");
const Lecturer = require("../../models/usersModels/lecturerModel");
const Student = require("../../models/usersModels/studentModel");
const { createNotification } = require("./notificationsController");
const { checkDeadline } = require("./sessionController");

const jwt = require("jsonwebtoken");
const crypto = require("crypto");
const multer = require("multer");
const path = require("path");
const fs = require("fs/promises");

let randomFileName;

const storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, "./uploads");
  },
  filename: function (req, file, cb) {
    const randomString = crypto.randomBytes(10).toString("hex");
    const fileExtension = path.extname(file.originalname);
    randomFileName = randomString + fileExtension; // Assign the generated name to the variable
    cb(null, randomFileName);
  },
});

const upload = multer({ storage: storage });

async function uploadFile(io, connectedUsers, req, res) {
  const token = req.headers.authorization;
  const { submissionType, projectType } = req.body; // Extract submissionType from req.body

  try {
    const submissionValidity = await checkDeadline(submissionType);

    if (submissionValidity.error) {
      return res.status(400).json({ error: submissionValidity.error });
    }

    if (!submissionValidity.isWithinDeadline) {
      return res
        .status(400)
        .json({ error: "Submission has been closed for this selection" });
    }

    const decoded = jwt.verify(token, process.env.SECRET_TOKEN);
    const studentId = decoded.user_id;
    const supervisorId = decoded.supervisor;
    const coSupervisorsIds = decoded.coSupervisors;
    const examinersIds = decoded.examiners;

    // Concatenate all IDs into a single array
    const studentLecturerIds = [
      supervisorId,
      ...coSupervisorsIds,
      ...examinersIds,
    ];
    const allowedSubmissionTypes = [
      "proposals",
      "progressOne",
      "progressTwo",
      "finalSubmission",
      "corrections",
      "presentationAndDemos",
      "finalReport",
      "proposalsExtras",
      "progressOneExtras",
      "progressTwoExtras",
      "finalSubmissionExtras",
      "correctionsExtras",
      "presentationAndDemosExtras",
      "finalReportExtras",
    ];
    // Check if the provided submissionType is in the allowed types array
    if (!allowedSubmissionTypes.includes(submissionType)) {
      return res.status(400).json({ error: "Invalid submission type" });
    }

    // Check if the deadline for the submissionType has passed

    let files = req.files; // Extract uploaded files

    // Save file info to the specified collection based on submissionType
    let fileSubmissionData;

    if (Array.isArray(files)) {
      // Handle multiple files for "others" submissionType
      fileSubmissionData = files.map((file) => ({
        originalName: file.originalname,
        autogeneratedName: file.filename,
        studentId,
        projectType,
        createdAt: new Date(),
        submissionType, // Include submissionType in the data
      }));
    } else {
      // Handle single file for other submissionTypes
      fileSubmissionData = [
        {
          originalName: files.originalname,
          autogeneratedName: files.filename,
          studentId,
          projectType,
          createdAt: new Date(),
          submissionType, // Include submissionType in the data
        },
      ];
    }

    // Call the saveDataSubmission function from your model with submissionType and fileSubmissionData
    await FileSubmission.saveDataSubmission(submissionType, fileSubmissionData);

    await createNotification({
      fromUser: studentId,
      message: "Student submitted a new file",
      toUsers: studentLecturerIds,
      creator: "Student",
      type: "Submission",
    });

    const usersSockets = studentLecturerIds
      .map((userId) => connectedUsers[userId])
      .filter(Boolean);

    if (usersSockets.length > 0) {
      io.to(usersSockets).emit("notification", {
        message: "Student submitted a new file",
        // Additional data if needed
        data: submissionType,
      });
    }

    return res
      .status(200)
      .json({ message: "File info uploaded successfully", fileSubmissionData });
  } catch (error) {
    console.error("Error uploading a file (fileUploadController): ", error);
    return res.status(500).json({ error: "Internal server error" });
  }
}

async function checkExistingSubmission(req, res) {
  const token = req.headers.authorization;
  const { submissionType, projectType } = req.body;

  try {
    const decoded = jwt.verify(token, process.env.SECRET_TOKEN);
    const studentId = decoded.user_id;
    const allowedSubmissionTypes = [
      "proposals",
      "progressOne",
      "progressTwo",
      "finalSubmission",
      "corrections",
      "presentationAndDemos",
      "finalReport",
      "proposalsExtras",
      "progressOneExtras",
      "progressTwoExtras",
      "finalSubmissionExtras",
      "correctionsExtras",
      "presentationAndDemosExtras",
      "finalReportExtras",
    ];
    if (!allowedSubmissionTypes.includes(submissionType)) {
      return res.status(400).json({ error: "Invalid submission type" });
    }
    if (submissionType.includes("Extras")) {
      // For "Extras" categories, skip the existingSubmission check
      return res
        .status(200)
        .json({ message: "No existing submission check required" });
    }

    const existingSubmission = await FileSubmission.checkExistingSubmission(
      submissionType,
      studentId,
      projectType
    );

    if (existingSubmission) {
      return res.status(400).json({
        message: "Submission already exists for this student and type",
      });
    }

    return res.status(200).json({ message: "No existing submission found" });
  } catch (error) {
    console.error(error);
    return res.status(500).json({ error: "Internal server error" });
  }
}

async function displayFile(req, res) {
  const { fileName } = req.params;
  const filePath = path.join("./uploads", fileName);

  try {
    // Read the file asynchronously
    const fileData = await fs.readFile(filePath);

    // Send the file data in the response
    res.end(fileData);
  } catch (error) {
    console.error(error);
    return res.status(404).json({ error: "File not found" });
  }
}

async function getStudentFiles(req, res) {
  const token = req.headers.authorization;
  const { submissionType, projectType } = req.query;
  try {
    const decoded = jwt.verify(token, process.env.SECRET_TOKEN);
    const studentId = decoded.user_id;
    const studentFiles = await FileSubmission.getFileSubmissionsByStudentId(
      submissionType,
      studentId,
      projectType
    );

    if (studentFiles.error) {
      return res.status(400).json({ error: studentFiles.error });
    }

    return res.status(200).json(studentFiles);
  } catch (error) {
    console.error(error);
    return res.status(500).json({ error: "Internal server error" });
  }
}

async function getProposalsForAdmin(req, res) {
  try {
    const { proposals, proposalsExtra } =
      await FileSubmission.getPendingProposalFilesForAdmin();

    if (proposals.length === 0) {
      return res.status(400).json({ error: "No pending proposal files found" });
    }
    const proposalsWithUserInfo = await Promise.all(
      proposals.map(async (proposal) => {
        const student = await Student.getUserById(proposal.studentId);
        const studentProposalsExtra = proposalsExtra.filter(
          (extra) => extra.studentId === proposal.studentId
        );
        return {
          ...proposal,
          studentName: student.username,
          studentProgram: student.user_program,
          studentMatricCard: student.matricCard,
          proposalsExtra: studentProposalsExtra,
        };
      })
    );

    res.status(200).json(proposalsWithUserInfo);
  } catch (error) {
    console.error(error);
    return res.status(500).json({ error: "Internal server error" });
  }
}

async function updateProposalStatusAndRemarks(req, res) {
  const { studentId, autogeneratedName, newStatus, newRemarks } = req.body;

  try {
    const result = await FileSubmission.updateProposalStatusAndRemarks(
      studentId,
      autogeneratedName,
      newStatus,
      newRemarks
    );

    return res.status(200).json(result);
  } catch (error) {
    console.error(error);
    return res
      .status(500)
      .json({ error: "Failed to update proposal status and remarks" });
  }
}

async function deleteFileByFileName(req, res) {
  const token = req.headers.authorization;
  const { fileName } = req.params;
  const { submissionType } = req.body;

  try {
    const decoded = jwt.verify(token, process.env.SECRET_TOKEN);
    const studentId = decoded.user_id;

    const deleteResult = await FileSubmission.deleteFileByName(
      submissionType,
      studentId,
      fileName
    );

    if (!deleteResult) {
      return res.status(404).json({ error: "File not found" });
    }

    // Delete the file from the uploads folder
    const filePath = path.join("./uploads", fileName);
    await fs.unlink(filePath);

    return res.status(200).json(deleteResult);
  } catch (error) {
    console.error(error);
    return res.status(500).json({ error: "Internal server error" });
  }
}
async function getAllLecturerStudentFiles(req, res) {
  const { projectType } = req.query;
  const collectionNames = [
    "progressOne",
    "progressTwo",
    "finalSubmission",
    "corrections",
    "presentationAndDemos",
    "finalReport",
    "proposalsExtras",
    "progressOneExtras",
    "progressTwoExtras",
    "finalSubmissionExtras",
    "correctionsExtras",
    "presentationAndDemosExtras",
    "finalReportExtras",
  ];

  try {
    const token = req.headers.authorization;
    const decoded = jwt.verify(token, process.env.SECRET_TOKEN);
    const lecturerId = decoded.user_id;
    const lecturer = await Lecturer.getUserById(lecturerId); // Fetch lecturer

    if (!lecturer) {
      return res.status(404).json({ error: "Lecturer not found" });
    }

    const allFiles = [];
    const userStudentsList = [
      ...lecturer.supervisedStudents,
      ...lecturer.coSupervisedStudents,
      ...lecturer.examinees,
    ];

    await Promise.all(
      collectionNames.map(async (collectionName) => {
        const filesPromises = userStudentsList.map(async (studentId) => {
          try {
            const student = await Student.getUserById(studentId);
            let studentType;
            if (lecturer.supervisedStudents.includes(studentId)) {
              studentType = "Supervised";
            } else if (lecturer.coSupervisedStudents.includes(studentId)) {
              studentType = "Co-Supervised";
            } else if (lecturer.examinees.includes(studentId)) {
              studentType = "Examinee";
            } else {
              studentType = "unknown";
            }

            const studentFiles =
              await FileSubmission.getFileSubmissionsByStudentId(
                collectionName,
                studentId,
                projectType
              );
            if (studentFiles.length) {
              const filesWithMetadata = studentFiles.map((file) => ({
                ...file,
                sType: collectionName,
                studentName: student.username,
                MatricNumber: student.matricCard,
                studentType: studentType,
                program: student.user_program,
              }));
              allFiles.push(...filesWithMetadata);
            }
          } catch (error) {
            console.error(
              `Error fetching ${collectionName} files for student ${studentId}:`,
              error
            );
          }
        });
        await Promise.all(filesPromises);
      })
    );
    return res.status(200).json(allFiles);
  } catch (error) {
    console.error("Error fetching all lecturer student files:", error);
    return res.status(500).json({ error: "Internal server error" });
  }
}

async function getAllLecturerProposalFiles(req, res) {
  try {
    const token = req.headers.authorization;
    const decoded = jwt.verify(token, process.env.SECRET_TOKEN);
    const lecturerId = decoded.user_id;
    const lecturer = await Lecturer.getUserById(lecturerId); // Fetch lecturer

    if (!lecturer) {
      return res.status(404).json({ error: "Lecturer not found" });
    }

    const allFiles = [];
    const userStudentsList = [
      ...lecturer.supervisedStudents,
      ...lecturer.coSupervisedStudents,
      ...lecturer.examinees,
    ];

    await Promise.all(
      userStudentsList.map(async (studentId) => {
        try {
          const student = await Student.getUserById(studentId);

          const studentFiles =
            await FileSubmission.getFileSubmissionsByStudentId(
              "proposals",
              studentId,
              "proposals"
            );
          if (studentFiles.length) {
            const filesWithMetadata = studentFiles.map((file) => ({
              ...file,
              sType: "proposals",
              studentName: student.username,
              MatricNumber: student.matricCard,
              program: student.user_program,
            }));
            allFiles.push(...filesWithMetadata);
          }
        } catch (error) {
          console.error(
            `Error fetching proposal files for student ${studentId}:`,
            error
          );
        }
      })
    );
    return res.status(200).json(allFiles);
  } catch (error) {
    console.error("Error fetching all lecturer proposal files:", error);
    return res.status(500).json({ error: "Internal server error" });
  }
}

async function getAllFilesForCoordinator(req, res) {
  const collectionNames = [
    "progressOne",
    "progressTwo",
    "finalSubmission",
    "corrections",
    "presentationAndDemos",
    "finalReport",
    "proposalsExtras",
    "progressOneExtras",
    "progressTwoExtras",
    "finalSubmissionExtras",
    "correctionsExtras",
    "presentationAndDemosExtras",
    "finalReportExtras",
  ];

  try {
    const token = req.headers.authorization;
    const decoded = jwt.verify(token, process.env.SECRET_TOKEN);
    const coordinatorProgram = decoded.coordinator_program;
    const programStudents = await Student.getAllStudentsByProgram(
      coordinatorProgram
    );
    const studentIds = programStudents.map((student) => student.user_id);
    const allFiles = [];
    await Promise.all(
      collectionNames.map(async (collectionName) => {
        const files = await FileSubmission.getAllFilesForCoordinator(
          collectionName
        );
        if (files.length) {
          const filteredFiles = files
            .filter((file) => studentIds.includes(file.studentId))
            .map((file) => ({
              ...file,
              studentName: programStudents.find(
                (student) => student.user_id === file.studentId
              ).username,
              matricCard: programStudents.find(
                (student) => student.user_id === file.studentId
              ).matricCard,
            }));

          allFiles.push(...filteredFiles);
        }
      })
    );
    return res.status(200).json(allFiles);
  } catch (error) {
    console.error("Error fetching all files for coordinator:", error);
    return res.status(500).json({ error: "Internal server error" });
  }
}

module.exports = {
  uploadFile,
  upload,
  checkExistingSubmission,
  getStudentFiles,
  displayFile,
  deleteFileByFileName,
  getAllLecturerProposalFiles,
  getProposalsForAdmin,
  updateProposalStatusAndRemarks,
  getAllLecturerStudentFiles,
  getAllFilesForCoordinator,
};
