const { firestore } = require("../../services/firebase");

class CVFile {
  constructor({ originalName, autogeneratedName, lecturerId, createdAt }) {
    this.originalName = originalName;
    this.autogeneratedName = autogeneratedName;
    this.lecturerId = lecturerId;
    this.createdAt = createdAt;
  }

  static async saveCVFile(cvFileData) {
    try {
      const cvFilesCollection = firestore().collection("nominationsCvFiles");
      const savedFiles = [];

      // Loop through each cvFileData item and save it individually
      for (const cvData of cvFileData) {
        const { lecturerId, originalName, autogeneratedName, createdAt } =
          cvData;

        const newCVFile = {
          originalName,
          autogeneratedName,
          lecturerId,
          createdAt,
        };

        const docRef = await cvFilesCollection.add(newCVFile);
        const savedFile = { ...newCVFile, id: docRef.id };
        savedFiles.push(savedFile);
      }

      return savedFiles;
    } catch (error) {
      throw error;
    }
  }
}

module.exports = CVFile;
