<template>
  <div>
    <div class="pt-10">
      <h1 class="title text-xl font-medium">{{ name }} Submission</h1>
      <p v-if="submissionDate" class="titleDes text-base font-light">
        Submission deadline:
        {{ formatDate(submissionDate[dateType].startDate) }} -
        {{ formatDate(submissionDate[dateType].endDate) }}
      </p>
      <p class="titleDes text-base font-light">
        Submission status:
        <span class="text-green-400 font-bold" v-if="isWithinDeadline"
          >Open</span
        >
        <span class="text-red-400 font-bold" v-else>Closed</span>
      </p>
      <p
        v-if="!submissionDate?.bypass_deadline"
        class="titleDes text-base font-light"
      >
        Time remaining:
        <span class="font-bold">{{ timeRemaining }}</span>
      </p>
      <small v-else class="font-semibold titleDes text-orange-400">
        *Note that the admin has turned off the deadline for submission
      </small>
    </div>
    <div class="pt-10 h-full lg:w-[80%]">
      <v-card
        v-for="(value, key) in filesInfo"
        :key="key"
        :title="
          key === 'Others' ? 'Other Files' : seperateName(name) + ' Files'
        "
        :elevation="2"
        :color="isDark ? '' : '#f5f5f5'"
        class="card title rounded-lg"
      >
        <template v-slot:text>
          <h1
            v-if="value.length > 0"
            class="cardValue uppercase text-lg text-gray-200"
            v-for="fileInfo in value"
            :key="fileInfo.autogeneratedName"
          >
            Uploeded File:
            <a
              :href="`${apiUrl}/files/${fileInfo.autogeneratedName}`"
              target="_blank"
              class="text-blue-800 dark:text-blue-400"
              rel="noopener noreferrer"
            >
              {{ fileInfo.originalName }}
            </a>
            <span
              @click="deleteFile(fileInfo.autogeneratedName, key)"
              class="text-red-500 pl-2 cursor-pointer capitalize"
            >
              Delete
            </span>
            <template v-if="props.type === 'proposals'">
              <div v-if="fileInfo.proposalStatus !== undefined">
                <div v-if="fileInfo.proposalStatus === 'pending'">
                  <p>
                    Proposal Status:
                    <span class="font-semibold">{{
                      fileInfo.proposalStatus
                    }}</span>
                  </p>
                </div>
                <div v-if="fileInfo.proposalStatus !== 'pending'">
                  <p>
                    Proposal Status:
                    <span
                      v-if="fileInfo.proposalStatus === 'accepted'"
                      class="font-semibold text-green-600"
                      >{{ fileInfo.proposalStatus }}</span
                    >
                    <span
                      v-if="fileInfo.proposalStatus === 'rejected'"
                      class="font-semibold text-red-500"
                      >{{ fileInfo.proposalStatus }}</span
                    >
                  </p>
                </div>
              </div>
              <div v-if="fileInfo.remarksFromCoordinator !== undefined">
                <p>
                  Remarks:
                  <span class="text-orange-100">{{
                    fileInfo.remarksFromCoordinator
                  }}</span>
                </p>
              </div>
            </template>
            <div>
              <p>
                Submitted at:
                <span class="text-orange-100 capitalize">{{
                  formatDate(fileInfo.createdAt)
                }}</span>
              </p>
            </div>
            <div>
              <p>
                <span class="capitalize">{{
                  submissionTimeDifference(fileInfo.createdAt)
                }}</span>
              </p>
            </div>
          </h1>
          <h1 v-else class="cardValue uppercase text-lg text-gray-200">
            No file was uploaded
          </h1>
        </template>
        <v-card-actions class="mb-2 mr-1">
          <v-spacer></v-spacer>
          <v-dialog v-model="dialog[key]" persistent width="1024">
            <template v-slot:activator="{ props }">
              <v-btn
                variant="elevated"
                v-bind="props"
                color="deep-purple-darken-4"
                size="large"
                class="w-48"
                :disabled="!isWithinDeadline"
                ><v-icon class="mr-2"><upload /></v-icon>Upload File</v-btn
              >
            </template>
            <v-card>
              <v-card-title>
                <span class="text-h5">Upload Files</span>
              </v-card-title>
              <v-form v-model="valid">
                <v-card-text>
                  <v-container>
                    <v-row>
                      <v-col cols="12">
                        <v-file-input
                          v-if="key === 'Main'"
                          v-model="mainFile"
                          variant="outlined"
                          clearable
                          :label="name + ' File'"
                          show-size
                          counter
                          :rules="[
                            (v) => !!v || 'File is required',
                            (v) => (v && v.length > 0) || 'File is required',
                          ]"
                        ></v-file-input>
                        <v-file-input
                          v-else
                          v-model="otherFiles"
                          multiple
                          variant="outlined"
                          chips
                          clearable
                          label="Other Files"
                          show-size
                          counter
                        ></v-file-input>
                        <small v-if="key === 'Main'"
                          >*Only One file is allowed, if you would like to
                          upload multiple files, you can use .rar or upload in
                          the "Others" section</small
                        >
                      </v-col>
                    </v-row>
                  </v-container>
                  <small
                    class="text-red-500 font-bold"
                    v-if="key === 'Main' && filesInfo.Main.length > 0"
                    >*Please Delete the old file first to upload a new
                    one</small
                  >
                  <v-alert
                    v-if="errorMessage"
                    type="error"
                    variant="outlined"
                    closable
                    >{{ errorMessage }}</v-alert
                  >
                </v-card-text>
                <v-card-actions>
                  <v-spacer></v-spacer>
                  <v-btn
                    color="warning"
                    class="w-32 cardValue"
                    variant="outlined"
                    @click="closeDialog(key)"
                  >
                    Close
                  </v-btn>
                  <v-btn
                    @click="
                      key === 'Main' ? submitMainFiles() : submitOtherFiles()
                    "
                    class="cardValue w-32"
                    variant="elevated"
                    color="indigo"
                    :disabled="
                      (key === 'Main' && filesInfo.Main.length > 0) || !valid
                    "
                  >
                    <v-icon class="mr-2"><upload /></v-icon>
                    Upload
                  </v-btn>
                </v-card-actions>
              </v-form>
            </v-card>
          </v-dialog>
        </v-card-actions>
      </v-card>
    </div>
    <v-snackbar
      :timeout="2000"
      color="indigo"
      variant="elevated"
      v-model="snackbar"
    >
      {{ snackbarMessage }}

      <template v-slot:actions>
        <v-btn color="white" variant="transparent" @click="snackbar = false">
          X
        </v-btn>
      </template>
    </v-snackbar>
    <div class="pt-10"></div>
  </div>
</template>

<script setup>
import upload from "@/assets/icons/upload.vue";
import { ref, onMounted, computed } from "vue";
import axios from "axios";
import { useDark } from "@vueuse/core";

// Constants
const props = defineProps({
  type: String,
  extrasType: String,
  name: String,
  projectType: String,
  dateType: String,
  submissionDate: Object,
});
// current time and date
const now = new Date();
const isDark = useDark();
const snackbar = ref(false);
const snackbarMessage = ref("");
const filesInfo = ref({
  Main: [],
  Others: [],
});
const mainFile = ref(null); // For single Main file
const otherFiles = ref([]); // For multiple other files
const dialog = ref({
  Main: false,
  Others: false,
});
const dialogTypes = {
  Main: "main",
  Others: "others",
};
const errorMessage = ref("");
const valid = ref(false);

const apiUrl = import.meta.env.VITE_API_URL;

// Functions

const closeDialog = (key) => {
  dialog.value[key] = false;
  if (key == "Main") {
    mainFile.value = null;
    errorMessage.value = "";
  } else {
    otherFiles.value = [];
    errorMessage.value = "";
  }
};

const seperateName = (name) => {
  const splitName = name.split(" ");
  const newName = splitName.join(" ");
  return newName;
};

const isWithinDeadline = computed(() => {
  if (props.submissionDate?.bypass_deadline === true) {
    return true;
  } else if (props.submissionDate) {
    const jsStartDate = new Date(
      props.submissionDate[props.dateType].startDate
    );
    const jsEndDate = new Date(props.submissionDate[props.dateType].endDate);
    const currentTime = now.getTime();

    return (
      currentTime >= jsStartDate.getTime() && currentTime <= jsEndDate.getTime()
    );
  }
  return false;
});

// time remaining for the deadline
const timeRemaining = computed(() => {
  if (props.submissionDate) {
    const jsEndDate = new Date(props.submissionDate[props.dateType].endDate);
    const currentTime = now.getTime();

    if (currentTime > jsEndDate.getTime()) {
      // Submission time has passed
      const timeDiff = currentTime - jsEndDate.getTime();
      const days = Math.floor(timeDiff / (1000 * 60 * 60 * 24));
      const hours = Math.floor(
        (timeDiff % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60)
      );

      if (days > 0) {
        return `Closed ${days} days ago`;
      } else {
        return `Closed ${hours} ${hours === 1 ? "hour" : "hours"} ago`;
      }
    } else {
      // Submission time is still remaining
      const timeDiff = jsEndDate.getTime() - currentTime;
      const days = Math.floor(timeDiff / (1000 * 60 * 60 * 24));
      const hours = Math.floor(
        (timeDiff % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60)
      );

      if (days > 0) {
        if (hours > 0) {
          return `${days} days and ${hours} ${
            hours === 1 ? "hour" : "hours"
          } remaining`;
        } else {
          return `${days} ${days === 1 ? "day" : "days"} remaining`;
        }
      } else {
        return `${hours} ${hours === 1 ? "hour" : "hours"} remaining`;
      }
    }
  }

  return "N/A";
});

const submissionTimeDifference = (createdAt) => {
  if (createdAt && props.submissionDate) {
    if (typeof createdAt === "string") {
      // Handle the case when createdAt is provided as a string
      const jsCreatedAt = new Date(createdAt);
      const jsEndDate = new Date(props.submissionDate[props.dateType].endDate);
      const timeDiff = jsEndDate.getTime() - jsCreatedAt.getTime();

      if (timeDiff < 0) {
        // Submitted after the end time
        const lateDays = Math.floor(Math.abs(timeDiff) / (1000 * 60 * 60 * 24));
        const lateHours = Math.floor(
          (Math.abs(timeDiff) % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60)
        );
        const lateMinutes = Math.floor(
          (Math.abs(timeDiff) % (1000 * 60 * 60)) / (1000 * 60)
        );

        const lateDaysText =
          lateDays > 0 ? `${lateDays} day${lateDays > 1 ? "s" : ""}` : "";
        const lateHoursText =
          lateHours > 0 ? `${lateHours} hour${lateHours > 1 ? "s" : ""}` : "";
        const lateMinutesText =
          lateMinutes > 0
            ? `${lateMinutes} minute${lateMinutes > 1 ? "s" : ""}`
            : "";

        const lateSubmissionText = `Submitted ${lateDaysText}${
          lateDays > 0 && (lateHours > 0 || lateMinutes > 0) ? " and " : ""
        }${lateHoursText}${
          lateHours > 0 && lateMinutes > 0 ? " and " : ""
        }${lateMinutesText} late`;

        return lateSubmissionText.trim();
      } else if (timeDiff === 0) {
        // Submitted exactly at the end time
        return "Submitted exactly on time";
      } else {
        // Submitted before the end time
        const earlyDays = Math.floor(timeDiff / (1000 * 60 * 60 * 24));
        const earlyHours = Math.floor(
          (timeDiff % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60)
        );
        const earlyMinutes = Math.floor(
          (timeDiff % (1000 * 60 * 60)) / (1000 * 60)
        );

        const earlyDaysText =
          earlyDays > 0 ? `${earlyDays} day${earlyDays > 1 ? "s" : ""}` : "";
        const earlyHoursText =
          earlyHours > 0
            ? `${earlyHours} hour${earlyHours > 1 ? "s" : ""}`
            : "";
        const earlyMinutesText =
          earlyMinutes > 0
            ? `${earlyMinutes} minute${earlyMinutes > 1 ? "s" : ""}`
            : "";

        const earlySubmissionText = `Submitted ${earlyDaysText}${
          earlyDays > 0 && (earlyHours > 0 || earlyMinutes > 0) ? " and " : ""
        }${earlyHoursText}${
          earlyHours > 0 && earlyMinutes > 0 ? " and " : ""
        }${earlyMinutesText} early`;

        return earlySubmissionText.trim();
      }
    } else if (createdAt && createdAt._seconds && createdAt._nanoseconds) {
      const jsCreatedAt = new Date(createdAt._seconds * 1000);
      const jsEndDate = new Date(props.submissionDate[props.dateType].endDate);
      const timeDiff = jsEndDate.getTime() - jsCreatedAt.getTime();

      if (timeDiff < 0) {
        // Submitted after the end time
        const lateDays = Math.floor(Math.abs(timeDiff) / (1000 * 60 * 60 * 24));
        const lateHours = Math.floor(
          (Math.abs(timeDiff) % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60)
        );
        const lateMinutes = Math.floor(
          (Math.abs(timeDiff) % (1000 * 60 * 60)) / (1000 * 60)
        );

        const lateDaysText =
          lateDays > 0 ? `${lateDays} day${lateDays > 1 ? "s" : ""}` : "";
        const lateHoursText =
          lateHours > 0 ? `${lateHours} hour${lateHours > 1 ? "s" : ""}` : "";
        const lateMinutesText =
          lateMinutes > 0
            ? `${lateMinutes} minute${lateMinutes > 1 ? "s" : ""}`
            : "";

        const lateSubmissionText = `Submitted ${lateDaysText}${
          lateDays > 0 && (lateHours > 0 || lateMinutes > 0) ? " and " : ""
        }${lateHoursText}${
          lateHours > 0 && lateMinutes > 0 ? " and " : ""
        }${lateMinutesText} late`;

        return lateSubmissionText.trim();
      } else if (timeDiff === 0) {
        // Submitted exactly at the end time
        return "Submitted exactly on time";
      } else {
        // Submitted before the end time
        const earlyDays = Math.floor(timeDiff / (1000 * 60 * 60 * 24));
        const earlyHours = Math.floor(
          (timeDiff % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60)
        );
        const earlyMinutes = Math.floor(
          (timeDiff % (1000 * 60 * 60)) / (1000 * 60)
        );

        const earlyDaysText =
          earlyDays > 0 ? `${earlyDays} day${earlyDays > 1 ? "s" : ""}` : "";
        const earlyHoursText =
          earlyHours > 0
            ? `${earlyHours} hour${earlyHours > 1 ? "s" : ""}`
            : "";
        const earlyMinutesText =
          earlyMinutes > 0
            ? `${earlyMinutes} minute${earlyMinutes > 1 ? "s" : ""}`
            : "";

        const earlySubmissionText = `Submitted ${earlyDaysText}${
          earlyDays > 0 && (earlyHours > 0 || earlyMinutes > 0) ? " and " : ""
        }${earlyHoursText}${
          earlyHours > 0 && earlyMinutes > 0 ? " and " : ""
        }${earlyMinutesText} early`;

        return earlySubmissionText.trim();
      }
    }
  }

  return "N/A";
};

onMounted(async () => {
  try {
    const token = localStorage.getItem("access_token");

    const payload = {
      projectType: props.projectType,
    };

    // Get main file
    try {
      const responseMain = await axios.get(`${apiUrl}/myfiles`, {
        params: {
          submissionType: props.type,
          ...payload,
        },
        headers: {
          Authorization: token,
          "Content-Type": "application/json",
        },
      });
      if (responseMain.data.length === 0) {
        filesInfo.value.Main = [];
      } else {
        filesInfo.value.Main = responseMain.data;
      }
    } catch (error) {
      // Handle error for main request
    }

    // Get other files
    try {
      const responseOthers = await axios.get(`${apiUrl}/myfiles`, {
        params: {
          submissionType: props.extrasType,
          ...payload,
        },
        headers: {
          Authorization: token,
          "Content-Type": "application/json",
        },
      });
      if (responseOthers.data.length === 0) {
        filesInfo.value.Others = [];
      } else {
        filesInfo.value.Others = responseOthers.data;
      }
    } catch (error) {
      // Handle error for other files request
    }
  } catch (error) {
    console.error("Error fetching user info:", error);
    // Handle overall error, display an error message, or redirect if needed
  }
});

const submitMainFiles = async () => {
  try {
    const token = localStorage.getItem("access_token");
    const formData = new FormData();

    if (mainFile.value) {
      const submissionCheckData = {
        projectType: props.projectType,
        submissionType: props.type, // Set the submission type for checking existing submission
      };

      // First request: Check for existing submission
      const existingSubmissionResponse = await axios.post(
        `${apiUrl}/checkExistingSubmission`,
        submissionCheckData,
        {
          headers: {
            Authorization: token,
            "Content-Type": "application/json",
          },
        }
      );

      if (
        existingSubmissionResponse.status === 400 &&
        existingSubmissionResponse.data.error
      ) {
        console.error("Submission already exists for this student and type.");
        errorMessage.value = existingSubmissionResponse.data.error;
        return; // Stop file upload process
      } else {
        // Reset the error message on successful upload
        errorMessage.value = "";
      }

      // If no existing submission, proceed with file upload
      formData.append("file", mainFile.value[0]);
      formData.append("submissionType", props.type);
      formData.append("projectType", props.projectType);

      const uploadFileResponse = await axios.post(
        `${apiUrl}/students/files/upload`,
        formData,
        {
          headers: {
            Authorization: token,
            "Content-Type": "multipart/form-data",
          },
        }
      );

      filesInfo.value.Main = uploadFileResponse.data.fileSubmissionData;
      dialog.value.Main = false;
      mainFile.value = null;
      snackbar.value = true;
      snackbarMessage.value = "File uploaded successfully.";
    } else {
      console.error("No Main file uploaded.");
    }
  } catch (error) {
    errorMessage.value = error.response.data.error;
  }
};

const submitOtherFiles = async () => {
  try {
    const token = localStorage.getItem("access_token");
    const formData = new FormData();

    if (otherFiles.value.length > 0) {
      otherFiles.value.forEach((file) => {
        formData.append("file", file);
      });
      formData.append("submissionType", props.extrasType);
      formData.append("projectType", props.projectType);

      const response = await axios.post(
        `${apiUrl}/students/files/upload`,
        formData,
        {
          headers: {
            Authorization: token,
            "Content-Type": "multipart/form-data",
          },
        }
      );
      filesInfo.value.Others.push(...response.data.fileSubmissionData);
      otherFiles.value = [];
      dialog.value.Others = false;
      snackbar.value = true;
      snackbarMessage.value = "File(s) uploaded successfully.";
    } else {
      console.error("No other files uploaded.");
    }
  } catch (error) {
    errorMessage.value = error.response.data.error;
  }
};

const deleteFile = async (autogeneratedName, dialogType) => {
  try {
    const token = localStorage.getItem("access_token");
    let submissionType = dialogTypes[dialogType];
    if (dialogType === "Main") {
      submissionType = props.type;
    } else if (dialogType === "Others") {
      submissionType = props.extrasType;
    }
    const response = await axios.delete(
      `${apiUrl}/students/files/${autogeneratedName}`,
      {
        headers: {
          Authorization: token,
          "Content-Type": "application/json",
        },
        // If submissionType is required in the request body, pass it here
        data: {
          submissionType, // Adjust if needed
        },
      }
    );
    // Handle success response if needed
    filesInfo.value[dialogType] = filesInfo.value[dialogType].filter(
      (file) => file.autogeneratedName !== autogeneratedName
    );
  } catch (error) {
    console.error("Error deleting file:", error);
  }
};

const formatDate = (createdAt) => {
  if (typeof createdAt === "string") {
    // Handle the case when createdAt is provided as a string
    const date = new Date(createdAt);
    return date.toLocaleString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "numeric",
      minute: "numeric",
    });
  } else if (createdAt && createdAt._seconds && createdAt._nanoseconds) {
    // Handle the case when createdAt is provided as an object with _seconds and _nanoseconds
    const date = new Date(createdAt._seconds * 1000);
    return date.toLocaleString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "numeric",
      minute: "numeric",
    });
  } else {
    // Handle other cases or return a default value
    return "Invalid Date";
  }
};
</script>

<style lang="scss" scoped>
.title {
  font-family: "DM Sans", sans-serif;
}
.titleDes {
  font-family: "DM Sans", sans-serif;
}
.cardValue {
  font-family: "Source Sans Pro", sans-serif;
}
.card {
  width: 100%;
}
.vBtn {
  height: 2.5rem !important;
  font-weight: 600;
}

.card:nth-child(2) {
  margin-top: 20px;
}
</style>
