<template>
  <div>
    <div class="pt-10">
      <h1 class="title text-xl font-medium">{{ name }} Submission</h1>
      <p v-if="submissionDate" class="titleDes text-base font-light">
        Don't forget to submit by {{ submissionDate[dateType] }}
      </p>
    </div>
    <div class="pt-10 h-full w-[80%]">
      <v-card
        v-for="(value, key) in filesInfo"
        :key="key"
        :title="
          key === 'Others' ? 'Other Files' : seperateName(name) + ' Files'
        "
        :elevation="2"
        :color="isDark ? '' : '#f5f5f5'"
        class="card title rounded-lg"
      >
        <template v-slot:subtitle>
          <h1
            v-if="value.length > 0"
            class="cardValue uppercase text-lg"
            v-for="fileInfo in value"
            :key="fileInfo.autogeneratedName"
          >
            <a
              :href="`http://localhost:8000/files/${fileInfo.autogeneratedName}`"
              target="_blank"
              rel="noopener noreferrer"
            >
              {{ fileInfo.originalName }}
            </a>
            <span
              @click="deleteFile(fileInfo.autogeneratedName, key)"
              class="text-red-500 pl-5 cursor-pointer capitalize"
            >
              Delete
            </span>
          </h1>
          <h1 v-else class="cardValue uppercase text-lg">
            No file was uploaded
          </h1>
        </template>
        <v-card-actions class="mb-2 mr-1">
          <v-spacer></v-spacer>
          <v-dialog v-model="dialog[key]" persistent width="1024">
            <template v-slot:activator="{ props }">
              <v-btn
                class=""
                variant="elevated"
                v-bind="props"
                color="deep-purple-darken-4"
                size="large"
                ><v-icon class="mr-2"><upload /></v-icon>Upload File</v-btn
              >
            </template>
            <v-card>
              <v-card-title>
                <span class="text-h5">Upload Files</span>
              </v-card-title>
              <v-card-text>
                <v-container>
                  <v-row>
                    <v-col cols="12">
                      <v-file-input
                        v-if="key === 'Main'"
                        v-model="mainFile"
                        variant="outlined"
                        clearable
                        :label="name + ' File'"
                        show-size
                        counter
                      ></v-file-input>
                      <v-file-input
                        v-else
                        v-model="otherFiles"
                        multiple
                        variant="outlined"
                        chips
                        clearable
                        label="Other Files"
                        show-size
                        counter
                      ></v-file-input>
                      <small v-if="key === 'Main'"
                        >*Only One file is allowed, if you would like to upload
                        multiple files, you can use .rar or upload in the
                        "Othres" section</small
                      >
                    </v-col>
                  </v-row>
                </v-container>
                <small
                  class="text-red-500 font-bold text-base"
                  v-if="key === 'Main' && filesInfo.Main.length > 0"
                  >*Please Delete the old file first to upload a new one</small
                >
                <v-alert
                  v-if="errorMessage"
                  type="warning"
                  variant="outlined"
                  closable
                  >{{ errorMessage }}</v-alert
                >
              </v-card-text>
              <v-card-actions>
                <v-spacer></v-spacer>
                <v-btn
                  color="warning"
                  class="w-32 cardValue"
                  variant="outlined"
                  @click="closeDialog(key)"
                >
                  Close
                </v-btn>
                <v-btn
                  @click="
                    key === 'Main' ? submitMainFiles() : submitOtherFiles()
                  "
                  class="cardValue w-32"
                  variant="elevated"
                  color="indigo"
                  :disabled="key === 'Main' && filesInfo.Main.length > 0"
                >
                  <v-icon class="mr-2"><upload /></v-icon>
                  Upload
                </v-btn>
              </v-card-actions>
            </v-card>
          </v-dialog>
        </v-card-actions>
      </v-card>
    </div>
    <div class="pt-10"></div>
  </div>
</template>

<script setup>
import upload from "@/assets/icons/upload.vue";
import { ref, onMounted } from "vue";
import axios from "axios";
import { useDark } from "@vueuse/core";

// Constants
const props = defineProps({
  type: String,
  extrasType: String,
  name: String,
  dateType: String,
});
const isDark = useDark();
const filesInfo = ref({
  Main: [],
  Others: [],
});
const mainFile = ref(null); // For single Main file
const otherFiles = ref([]); // For multiple other files
const dialog = ref({
  Main: false,
  Others: false,
});
const dialogTypes = {
  Main: "main",
  Others: "others",
};
const submissionDate = ref(null);
const errorMessage = ref("");
// Functions

const closeDialog = (key) => {
  dialog.value[key] = false;
  if (key == "Main") {
    mainFile.value = null;
  } else {
    otherFiles.value = [];
  }
};

const seperateName = (name) => {
  const splitName = name.split(" ");
  const newName = splitName.join(" ");
  return newName;
};

onMounted(async () => {
  try {
    const token = localStorage.getItem("access_token");

    // Get main file
    try {
      const responseMain = await axios.get(
        `http://localhost:8000/myfiles?submissionType=${props.type}`,
        {
          headers: {
            Authorization: token,
            "Content-Type": "application/json",
          },
        }
      );
      if (responseMain.data.length === 0) {
        filesInfo.value.Main = [];
      } else {
        filesInfo.value.Main = responseMain.data;
      }
    } catch (error) {
      // Handle error for main request
    }

    // Get other files
    try {
      const responseOthers = await axios.get(
        `http://localhost:8000/myfiles?submissionType=${props.extrasType}`,
        {
          headers: {
            Authorization: token,
            "Content-Type": "application/json",
          },
        }
      );
      if (responseOthers.data.length === 0) {
        filesInfo.value.Others = [];
      } else {
        filesInfo.value.Others = responseOthers.data;
      }
    } catch (error) {
      // Handle error for other files request
    }

    // Get Date deadline
    try {
      const response = await axios.get(`http://localhost:8000/currentSession`);
      submissionDate.value = response.data;
    } catch (error) {
      console.error(`Error fetching ${dateType} deadline:`, error);
      // Handle error for  deadline request
    }
  } catch (error) {
    console.error("Error fetching user info:", error);
    // Handle overall error, display an error message, or redirect if needed
  }
});

const submitMainFiles = async () => {
  console.log("Submitting Main Files...");
  try {
    const token = localStorage.getItem("access_token");
    const formData = new FormData();

    if (mainFile.value) {
      const submissionCheckData = {
        submissionType: props.type, // Set the submission type for checking existing submission
      };

      // First request: Check for existing submission
      const existingSubmissionResponse = await axios.post(
        "http://localhost:8000/checkExistingSubmission",
        submissionCheckData,
        {
          headers: {
            Authorization: token,
            "Content-Type": "application/json",
          },
        }
      );

      if (
        existingSubmissionResponse.status === 400 &&
        existingSubmissionResponse.data.error
      ) {
        console.error("Submission already exists for this student and type.");
        errorMessage.value = existingSubmissionResponse.data.error;
        // Handle existing submission error here
        return; // Stop file upload process
      } else {
        // Reset the error message on successful upload
        errorMessage.value = "";
      }

      // If no existing submission, proceed with file upload
      formData.append("file", mainFile.value[0]);
      formData.append("submissionType", props.type);

      const uploadFileResponse = await axios.post(
        "http://localhost:8000/uploadFile",
        formData,
        {
          headers: {
            Authorization: token,
            "Content-Type": "multipart/form-data",
          },
        }
      );

      filesInfo.value.Main = uploadFileResponse.data.fileSubmissionData;
      dialog.value.Main = false;
      mainFile.value = null;
    } else {
      console.error("No Main file uploaded.");
      console.log("mainFile:", mainFile.value);
    }
  } catch (error) {
    console.error("Error uploading Main file:", error);
    errorMessage.value = error.response.data.message;
  }
};

const submitOtherFiles = async () => {
  try {
    const token = localStorage.getItem("access_token");
    const formData = new FormData();

    if (otherFiles.value.length > 0) {
      otherFiles.value.forEach((file) => {
        formData.append("file", file);
      });
      formData.append("submissionType", props.extrasType);

      const response = await axios.post(
        "http://localhost:8000/uploadFile",
        formData,
        {
          headers: {
            Authorization: token,
            "Content-Type": "multipart/form-data",
          },
        }
      );
      filesInfo.value.Others.push(...response.data.fileSubmissionData);
      otherFiles.value = [];
      dialog.value.Others = false;
    } else {
      console.error("No other files uploaded.");
      console.log("otherFiles:", otherFiles.value);
    }
  } catch (error) {
    console.error("Error uploading other files:", error);
  }
};

const deleteFile = async (autogeneratedName, dialogType) => {
  try {
    const token = localStorage.getItem("access_token");
    let submissionType = dialogTypes[dialogType];
    if (dialogType === "Main") {
      submissionType = props.type;
    } else if (dialogType === "Others") {
      submissionType = props.extrasType;
    }
    const response = await axios.delete(
      `http://localhost:8000/deleteFile/${autogeneratedName}`,
      {
        headers: {
          Authorization: token,
          "Content-Type": "application/json",
        },
        // If submissionType is required in the request body, pass it here
        data: {
          submissionType, // Adjust if needed
        },
      }
    );
    // Handle success response if needed
    filesInfo.value[dialogType] = filesInfo.value[dialogType].filter(
      (file) => file.autogeneratedName !== autogeneratedName
    );
    console.log("File deleted:", response.data);
  } catch (error) {
    console.error("Error deleting file:", error);
    // Handle error if needed
  }
};
// const rules = ref([
//   (files) =>
//     !files ||
//     !files.some((file) => file.size > 2000000) ||
//     "File size should be less than 2 MB!",
// ]);
</script>

<style lang="scss" scoped>
.title {
  font-family: "DM Sans", sans-serif;
}
.titleDes {
  font-family: "DM Sans", sans-serif;
}
.cardValue {
  font-family: "Source Sans Pro", sans-serif;
}
.card {
  width: 100%;
}
.vBtn {
  height: 2.5rem !important;
  font-weight: 600;
}

.card:nth-child(2) {
  margin-top: 20px;
}
</style>
