<template>
  <div>
    <div class="pt-10">
      <h1 class="title text-xl font-medium">Proposal Submission</h1>
      <p class="titleDes text-base font-light">Don't forget to submit by</p>
    </div>
    <div class="pt-10 h-full w-2/3">
      <div
        v-for="(value, key) in filesInfo"
        :key="key"
        class="card drop-shadow-lg flex flex-row items-center justify-between p-10 rounded-lg bg-[#f5f5f5] dark:bg-gray-800"
      >
        <div class="flex flex-col w-full">
          <h1 class="title font-bold capitalize w-16 text-lg">{{ key }}</h1>
          <h1
            v-if="value.length > 0"
            class="cardValue uppercase text-lg pl-20"
            v-for="fileInfo in value"
            :key="fileInfo.autogeneratedName"
          >
            <a
              :href="`http://localhost:8000/getFile/${fileInfo.autogeneratedName}`"
              target="_blank"
              rel="noopener noreferrer"
            >
              {{ fileInfo.originalName }}
            </a>
          </h1>
          <h1 v-else class="cardValue uppercase text-lg pl-20">
            No file was uploaded
          </h1>
        </div>
        <div>
          <v-row>
            <v-dialog v-model="dialog[key]" persistent width="1024">
              <template v-slot:activator="{ props }">
                <v-btn
                  class="w-56"
                  variant="elevated"
                  v-bind="props"
                  color="grey-darken-4"
                  size="large"
                  >Upload File</v-btn
                >
              </template>
              <v-card>
                <v-card-title>
                  <span class="text-h5">Upload Files</span>
                </v-card-title>
                <v-card-text>
                  <v-container>
                    <v-row>
                      <v-col cols="12">
                        <v-file-input
                          v-if="key === 'Proposal'"
                          v-model="proposalFile"
                          clearable
                          label="Proposal File"
                          show-size
                          counter
                        ></v-file-input>
                        <v-file-input
                          v-else
                          v-model="otherFiles"
                          multiple
                          chips
                          clearable
                          label="Other Files"
                          show-size
                          counter
                        ></v-file-input>
                      </v-col>
                    </v-row>
                  </v-container>
                </v-card-text>
                <v-card-actions>
                  <v-spacer></v-spacer>
                  <v-btn
                    color="warning"
                    class="w-32 cardValue"
                    variant="outlined"
                    @click="dialog[key] = false"
                  >
                    Close
                  </v-btn>
                  <v-btn
                    @click="
                      key === 'Proposal'
                        ? submitProposalFiles()
                        : submitOtherFiles()
                    "
                    class="cardValue"
                    variant="elevated"
                  >
                    <v-icon class="mr-2"><upload /></v-icon>
                    Upload
                  </v-btn>
                </v-card-actions>
              </v-card>
            </v-dialog>
          </v-row>
        </div>
      </div>
    </div>
    <div class="pt-10"></div>
  </div>
</template>

<script setup>
import upload from "@/assets/icons/upload.vue";
import { ref, onMounted } from "vue";
import axios from "axios";

// Constants
const filesInfo = ref({
  Proposal: [],
  Others: [],
});
const proposalFile = ref(null); // For single proposal file
const otherFiles = ref([]); // For multiple other files
const dialog = ref({
  Proposal: false,
  Others: false,
});
// Functions
onMounted(async () => {
  try {
    const token = localStorage.getItem("access_token");

    // Get proposals
    const responseProposal = await axios.get(
      `http://localhost:8000/myfiles?submissionType=proposals`,
      {
        headers: {
          Authorization: token,
          "Content-Type": "application/json",
        },
      }
    );

    filesInfo.value.Proposal = responseProposal.data;

    // Get other files
    const responseOthers = await axios.get(
      `http://localhost:8000/myfiles?submissionType=others`,
      {
        headers: {
          Authorization: token,
          "Content-Type": "application/json",
        },
      }
    );

    filesInfo.value.Others = responseOthers.data;
  } catch (error) {
    console.error("Error fetching user info:", error);
    // Handle error, display an error message, or redirect if needed
  }
});

const submitProposalFiles = async () => {
  try {
    const token = localStorage.getItem("access_token");
    const formData = new FormData();

    if (proposalFile.value) {
      const submissionCheckData = {
        submissionType: "proposals", // Set the submission type for checking existing submission
      };

      // First request: Check for existing submission
      const existingSubmissionResponse = await axios.post(
        "http://localhost:8000/checkExistingSubmission",
        submissionCheckData,
        {
          headers: {
            Authorization: token,
            "Content-Type": "application/json",
          },
        }
      );

      if (
        existingSubmissionResponse.status === 400 &&
        existingSubmissionResponse.data.error
      ) {
        console.error("Submission already exists for this student and type.");
        // Handle existing submission error here
        return; // Stop file upload process
      }

      // If no existing submission, proceed with file upload
      formData.append("file", proposalFile.value[0]);
      formData.append("submissionType", "proposals");

      const uploadFileResponse = await axios.post(
        "http://localhost:8000/uploadFile",
        formData,
        {
          headers: {
            Authorization: token,
            "Content-Type": "multipart/form-data",
          },
        }
      );

      console.log("Proposal File Uploaded:", uploadFileResponse.data);
      dialog["Proposal"] = false;
    } else {
      console.error("No proposal file uploaded.");
      console.log("proposalFile:", proposalFile.value);
    }
  } catch (error) {
    console.error("Error uploading proposal file:", error);
  }
};

const submitOtherFiles = async () => {
  try {
    const token = localStorage.getItem("access_token");
    const formData = new FormData();

    if (otherFiles.value.length > 0) {
      otherFiles.value.forEach((file) => {
        formData.append("file", file);
      });
      formData.append("submissionType", "others");

      const response = await axios.post(
        "http://localhost:8000/uploadFile",
        formData,
        {
          headers: {
            Authorization: token,
            "Content-Type": "multipart/form-data",
          },
        }
      );

      console.log("Other Files Uploaded:", response.data);
      dialog["Others"] = false;
    } else {
      console.error("No other files uploaded.");
      console.log("otherFiles:", otherFiles.value);
    }
  } catch (error) {
    console.error("Error uploading other files:", error);
  }
};
</script>

<style lang="scss" scoped>
.title {
  font-family: "DM Sans", sans-serif;
}
.titleDes {
  font-family: "DM Sans", sans-serif;
}
.cardValue {
  font-family: "Source Sans Pro", sans-serif;
}
.card {
  width: 100%;
}
.vBtn {
  height: 2.5rem !important;
  font-weight: 600;
}

.card:nth-child(2) {
  margin-top: 20px;
}
</style>
