<template>
  <div class="mt-10">
    <div class="lg:w-4/5">
      <div>
        <div class="w-fit m-auto mt-10">
          <v-tabs
            class="rounded-3xl md:px-20"
            align-tabs="center"
            :bg-color="isDark ? '#fdfefb' : '#BDBDBD'"
            v-model="tabSecondry"
          >
            <v-tab value="one">Proposals</v-tab>
            <v-tab value="two">Project 1</v-tab>
            <v-tab value="three">Project 2</v-tab>
          </v-tabs>
        </div>
        <div class="pl-0 w-full">
          <v-window disabled v-model="tabSecondry">
            <v-window-item value="one">
              <h1 class="title text-lg font-medium mt-5 mb-2">
                Student Proposals
                <span v-if="isLoading"
                  ><v-progress-circular
                    :size="22"
                    indeterminate
                  ></v-progress-circular
                ></span>
              </h1>
              <div v-if="!isLoading && proposals.length > 0">
                <v-card :rounded="0" :elevation="0">
                  <v-text-field
                    v-model="searchP"
                    label="Search"
                    prepend-inner-icon="mdi-magnify"
                    single-line
                    :rounded="0"
                    variant="outlined"
                    hide-details
                  ></v-text-field>
                </v-card>
                <v-data-table
                  v-if="proposals.length > 0"
                  :headers="headersProposals"
                  :items="proposals"
                  :search="searchP"
                >
                  <template v-slot:item.autogeneratedName="{ item }">
                    <a
                      :href="`${apiUrl}/files/${item.autogeneratedName}`"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      <span class="underline text-blue-800 dark:text-blue-400">
                        {{ item.autogeneratedName }}</span
                      >
                    </a>
                  </template>
                  <template v-slot:item.proposalStatus="{ item }">
                    <v-chip color="cyan" class="uppercase">
                      {{ item.proposalStatus }}
                    </v-chip>
                  </template>
                </v-data-table>
              </div>
              <v-skeleton-loader
                v-if="isLoading"
                class="mw-auto border"
                type="table"
              ></v-skeleton-loader>
              <v-alert
                v-if="proposals.length === 0 && !isLoading"
                type="info"
                variant="outlined"
                class="my-4"
                text="No proposals were submitted yet"
              ></v-alert>
            </v-window-item>
            <v-window-item value="two">
              <h1 class="title text-lg font-medium mt-5 mb-2">
                Student submissions for <strong>Project 1</strong>
                <span class="ml-2" v-if="isLoading"
                  ><v-progress-circular
                    :size="22"
                    indeterminate
                  ></v-progress-circular
                ></span>
              </h1>
              <div v-if="!isLoading && studentsPOne.length > 0">
                <v-card :rounded="0" :elevation="0">
                  <v-text-field
                    v-model="searchP1"
                    label="Search"
                    prepend-inner-icon="mdi-magnify"
                    single-line
                    :rounded="0"
                    variant="outlined"
                    hide-details
                  ></v-text-field>
                </v-card>
                <v-data-table
                  class="border"
                  :headers="headers"
                  :items="studentsPOne"
                  :search="searchP1"
                >
                  <template v-slot:item.numSubmissions="{ item }">
                    {{ item.submissions.length }}
                  </template>
                  <template v-slot:item.index="{ item }">
                    <v-btn
                      @click="openSubmissionsDialog(item)"
                      size="small"
                      color="primary"
                    >
                      Submissions
                    </v-btn>
                    <v-dialog v-model="item.submissionsDialog" width="1200">
                      <v-card title="Student Files For Project 1">
                        <v-card-text class="mt-4">
                          <v-data-table
                            class="border"
                            :headers="studentHeaders"
                            :items="item.submissions"
                          >
                            <template v-slot:item.autogeneratedName="{ item }">
                              <a
                                :href="`${apiUrl}/files/${item.autogeneratedName}`"
                                target="_blank"
                                rel="noopener noreferrer"
                              >
                                <span class="underline text-blue-200">
                                  {{ item.autogeneratedName }}</span
                                >
                              </a>
                            </template>
                          </v-data-table>
                        </v-card-text>

                        <v-card-actions>
                          <v-spacer></v-spacer>
                          <v-btn
                            color="warning"
                            variant="outlined"
                            class="w-32"
                            text="Cancel"
                            @click="closeDialogs(item)"
                          ></v-btn>
                        </v-card-actions>
                      </v-card>
                    </v-dialog>
                  </template>
                  <template v-slot:item.evaluation="{ item }">
                    <v-btn
                      @click="openEvaluationDialog(item)"
                      size="small"
                      color="indigo"
                    >
                      Evaluate
                    </v-btn>
                    <v-dialog v-model="item.evaluationDialog" width="1200">
                      <v-card>
                        <v-card-text>
                          <SingleEvaluation
                            :studentInfo="studentInfo"
                            :criteriasData="criteriasData"
                            :studentType="studentType"
                            :projectType="'pOne'"
                          />
                        </v-card-text>
                        <v-card-actions>
                          <v-spacer></v-spacer>
                          <v-btn
                            color="warning"
                            variant="outlined"
                            class="w-32"
                            text="Cancel"
                            @click="closeDialogs(item)"
                          ></v-btn>
                        </v-card-actions>
                      </v-card>
                    </v-dialog>
                  </template>
                </v-data-table>
              </div>
              <v-skeleton-loader
                v-if="isLoading"
                class="mw-auto border"
                type="table"
              ></v-skeleton-loader>

              <v-alert
                v-if="studentsPOne.length === 0 && !isLoading"
                type="info"
                variant="outlined"
                class="my-4"
                text="Student has not submitted any files yet for Project 1"
              ></v-alert>
            </v-window-item>
            <v-window-item value="three">
              <h1 class="title text-lg font-medium mt-5 mb-2">
                Student submissions for <strong>Project 2</strong>
                <span class="ml-2" v-if="isLoading"
                  ><v-progress-circular
                    :size="22"
                    indeterminate
                  ></v-progress-circular
                ></span>
              </h1>
              <div v-if="!isLoading && studentsPTwo.length > 0">
                <v-card :rounded="0" :elevation="0">
                  <v-text-field
                    v-model="searchP2"
                    label="Search"
                    prepend-inner-icon="mdi-magnify"
                    single-line
                    :rounded="0"
                    variant="outlined"
                    hide-details
                  ></v-text-field>
                </v-card>
                <v-data-table
                  class="border"
                  :headers="headers"
                  :items="studentsPTwo"
                  :search="searchP2"
                >
                  <template v-slot:item.numSubmissions="{ item }">
                    {{ item.submissions.length }}
                  </template>
                  <template v-slot:item.index="{ item }">
                    <v-btn
                      @click="openSubmissionsDialog(item)"
                      size="small"
                      color="primary"
                    >
                      Submissions
                    </v-btn>
                    <v-dialog v-model="item.submissionsDialog" width="1200">
                      <v-card title="Student Files For Project 2">
                        <v-card-text class="mt-4">
                          <v-data-table
                            class="border"
                            :headers="studentHeaders"
                            :items="item.submissions"
                          >
                            <template v-slot:item.autogeneratedName="{ item }">
                              <a
                                :href="`${apiUrl}/files/${item.autogeneratedName}`"
                                target="_blank"
                                rel="noopener noreferrer"
                              >
                                <span class="underline text-blue-200">
                                  {{ item.autogeneratedName }}</span
                                >
                              </a>
                            </template>
                          </v-data-table>
                        </v-card-text>

                        <v-card-actions>
                          <v-spacer></v-spacer>
                          <v-btn
                            color="warning"
                            variant="outlined"
                            class="w-32"
                            text="Cancel"
                            @click="closeDialogs(item)"
                          ></v-btn>
                        </v-card-actions>
                      </v-card>
                    </v-dialog>
                  </template>
                  <template v-slot:item.evaluation="{ item }">
                    <v-btn
                      @click="openEvaluationDialog(item)"
                      size="small"
                      color="indigo"
                    >
                      Evaluate
                    </v-btn>
                    <v-dialog v-model="item.evaluationDialog" width="1200">
                      <v-card>
                        <v-card-text>
                          <SingleEvaluation
                            :studentInfo="studentInfo"
                            :criteriasData="criteriasData"
                            :studentType="studentType"
                            :projectType="'pTwo'"
                          />
                        </v-card-text>
                        <v-card-actions>
                          <v-spacer></v-spacer>
                          <v-btn
                            color="warning"
                            variant="outlined"
                            class="w-32"
                            text="Cancel"
                            @click="closeDialogs(item)"
                          ></v-btn>
                        </v-card-actions>
                      </v-card>
                    </v-dialog>
                  </template>
                </v-data-table>
              </div>
              <v-skeleton-loader
                v-if="isLoading"
                class="mw-auto border"
                type="table"
              ></v-skeleton-loader>
              <v-alert
                v-if="studentsPTwo.length === 0 && !isLoading"
                type="info"
                variant="outlined"
                class="my-4"
                text="Student has not submitted any files yet for Project 2"
              ></v-alert>
            </v-window-item>
          </v-window>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from "vue";
import axios from "axios";
import { useDark } from "@vueuse/core";
import SingleEvaluation from "./singleEvaluation.vue";

// Constants

const isDark = useDark();
const tabSecondry = ref("");
const filesSubmissionPOne = ref([]);
const filesSubmissionPTwo = ref([]);
const proposals = ref([]);
const studentsPOne = ref([]);
const studentsPTwo = ref([]);
const studentInfo = ref({});
const criteriasData = ref([]);
const studentType = ref("");
const isLoading = ref(false);
const searchP = ref("");
const searchP1 = ref("");
const searchP2 = ref("");
const headers = ref([
  { key: "studentName", sortable: false, title: "Student Name" },
  { key: "MatricNumber", sortable: false, title: "Matric Number" },
  { key: "studentType", sortable: true, title: "Student Type" },
  { key: "numSubmissions", sortable: false, title: "No. of Submissions" },
  { key: "index", sortable: false, title: "Action" },
  { key: "evaluation", sortable: false, title: "Evaluation" },
]);
const studentHeaders = ref([
  { key: "originalName", sortable: false, title: "File Name" },
  { key: "createdAt", sortable: true, title: "Submission Date" },
  { key: "sType", sortable: true, title: "Submission Type" },
  { key: "autogeneratedName", sortable: false, title: "File" },
]);
const headersProposals = ref([
  { key: "originalName", sortable: false, title: "File Name" },
  { key: "autogeneratedName", sortable: false, title: "File" },
  { key: "studentName", sortable: false, title: "Student" },
  { key: "createdAt", sortable: true, title: "Submission Date" },
  { key: "proposalStatus", sortable: true, title: "Status" },
]);
const apiUrl = import.meta.env.VITE_API_URL;

// Functions

onMounted(async () => {
  isLoading.value = true;
  try {
    const token = localStorage.getItem("access_token");
    const response1 = await axios.get(
      `${apiUrl}/lecturer/myfiles?projectType=pOne`,
      {
        headers: { Authorization: token },
      }
    );
    filesSubmissionPOne.value = response1.data.map((file) => ({
      ...file,
      createdAt: formatDate(file.createdAt),
      sType: separateName(file.sType),
    }));
    aggregateStudents(filesSubmissionPOne, studentsPOne);
  } catch (error) {
    console.error("Error fetching files:", error);
  }

  try {
    const token = localStorage.getItem("access_token");
    const response2 = await axios.get(
      `${apiUrl}/lecturer/myfiles?projectType=pTwo`,
      {
        headers: { Authorization: token },
      }
    );
    filesSubmissionPTwo.value = response2.data.map((file) => ({
      ...file,
      createdAt: formatDate(file.createdAt),
      sType: separateName(file.sType),
    }));
    aggregateStudents(filesSubmissionPTwo, studentsPTwo);
  } catch (error) {
    console.error("Error fetching files:", error);
  }
  try {
    const token = localStorage.getItem("access_token");
    const response3 = await axios.get(`${apiUrl}/lecturer/myfiles/proposals`, {
      headers: { Authorization: token },
    });
    proposals.value = response3.data.map((file) => ({
      ...file,
      createdAt: formatDate(file.createdAt),
      sType: separateName(file.sType),
    }));
  } catch (error) {
    console.error("Error fetching files:", error);
  }
  isLoading.value = false;
  try {
    const responseCriteria = await axios.get(`${apiUrl}/api/criterias`);
    if (responseCriteria.status === 200) {
      criteriasData.value = responseCriteria.data;
    } else {
      console.error(
        "Error fetching evaluation criteria:",
        responseCriteria.data
      );
    }
  } catch (error) {
    console.error("Error fetching evaluation criteria:", error);
  }
});

const aggregateStudents = (type, student) => {
  const studentsMap = {};
  type.value.forEach((file) => {
    if (!studentsMap[file.studentId]) {
      studentsMap[file.studentId] = {
        studentId: file.studentId,
        studentName: file.studentName,
        MatricNumber: file.MatricNumber,
        studentType: file.studentType,
        createdAt: file.createdAt,
        program: file.program,
        submissions: [],
      };
    }
    studentsMap[file.studentId].submissions.push(file);
  });
  student.value = Object.values(studentsMap);
};

const formatDate = (timestamp) => {
  const date = new Date(timestamp._seconds * 1000); // Convert seconds to milliseconds
  return date.toLocaleString("en-UK", {
    year: "numeric",
    day: "numeric",
    month: "numeric",
    hour: "numeric",
    minute: "numeric",
    hour12: true,
  }); // Format the date as per the locale
};

const separateName = (name) => {
  const splitName = name.split(/(?=[A-Z0-9])/);
  const newName = splitName
    .map((word) => {
      return word.charAt(0).toUpperCase() + word.slice(1);
    })
    .join(" ");

  return newName;
};

const openSubmissionsDialog = (item) => {
  item.submissionsDialog = true;
  item.evaluationDialog = false; // Close Evaluation Dialog
};

// Open Evaluation Dialog
const openEvaluationDialog = (item) => {
  studentInfo.value = {
    id: item.studentId,
    name: item.studentName,
    program: item.program,
    MatricNumber: item.MatricNumber,
    type: item.studentType,
  };
  if (item.studentType === "Examinee") {
    studentType.value = "Examiner";
  } else {
    studentType.value = "Supervisor";
  }
  item.evaluationDialog = true;
  item.submissionsDialog = false; // Close Submissions Dialog
};

// Close Dialogs
const closeDialogs = (item) => {
  item.submissionsDialog = false;
  item.evaluationDialog = false;
};
</script>

<style lang="scss" scoped>
.title {
  font-family: "DM Sans", sans-serif;
  font-weight: 400;
  font-size: 1.125rem /* 18px */;
  line-height: 1.75rem /* 28px */;
}
.titleDes {
  font-family: "Work Sans", sans-serif;
  font-size: 1rem /* 18px */;
  line-height: 1.75rem /* 28px */;
}
</style>
