<template>
  <div class="mt-10">
    <div class="w-1/2">
      <h1 class="title text-lg font-medium">Student files submissions</h1>
    </div>
    <div class="w-4/5 mt-5">
      <v-card :rounded="0" :elevation="0">
        <v-text-field
          v-model="search"
          label="Search"
          prepend-inner-icon="mdi-magnify"
          single-line
          :rounded="0"
          variant="outlined"
          hide-details
        ></v-text-field>
      </v-card>
      <v-data-table
        class="border"
        :headers="headers"
        :items="students"
        :search="search"
      >
        <template v-slot:item.numSubmissions="{ item }">
          {{ item.submissions.length }}
        </template>
        <template v-slot:item.index="{ item }">
          <v-btn
            @click="openSubmissionsDialog(item)"
            size="small"
            color="primary"
          >
            Submissions
          </v-btn>
          <v-dialog v-model="item.submissionsDialog" width="1200">
            <v-card title="Student Files ">
              <v-card-text class="mt-4">
                <v-data-table
                  class="border"
                  :headers="studentHeaders"
                  :items="item.submissions"
                >
                  <template v-slot:item.autogeneratedName="{ item }">
                    <a
                      :href="`${apiUrl}/files/${item.autogeneratedName}`"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      <span class="underline text-blue-200">
                        {{ item.autogeneratedName }}</span
                      >
                    </a>
                  </template>
                </v-data-table>
              </v-card-text>

              <v-card-actions>
                <v-spacer></v-spacer>
                <v-btn
                  color="warning"
                  variant="outlined"
                  class="w-32"
                  text="Cancel"
                  @click="closeDialogs(item)"
                ></v-btn>
              </v-card-actions>
            </v-card>
          </v-dialog>
        </template>
        <template v-slot:item.evaluation="{ item }">
          <v-btn
            @click="openEvaluationDialog(item)"
            size="small"
            color="indigo"
          >
            Evaluate
          </v-btn>
          <v-dialog v-model="item.evaluationDialog" width="1200">
            <v-card>
              <v-card-text>
                <SingleEvaluation
                  :studentInfo="studentInfo"
                  :criteriasData="criteriasData"
                />
              </v-card-text>
              <v-card-actions>
                <v-spacer></v-spacer>
                <v-btn
                  color="warning"
                  variant="outlined"
                  class="w-32"
                  text="Cancel"
                  @click="closeDialogs(item)"
                ></v-btn>
              </v-card-actions>
            </v-card>
          </v-dialog>
        </template>
      </v-data-table>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from "vue";
import axios from "axios";
import { useDark } from "@vueuse/core";
import SingleEvaluation from "./singleEvaluation.vue";

// Constants

const isDark = useDark();
const filesSubmission = ref([]);
const students = ref([]);
const studentInfo = ref({});
const criteriasData = ref([]);
const search = ref("");
const headers = ref([
  { key: "studentName", sortable: false, title: "Student Name" },
  { key: "MatricNumber", sortable: false, title: "Matric Number" },
  { key: "studentType", sortable: true, title: "Student Type" },
  { key: "numSubmissions", sortable: true, title: "No. of Submissions" },
  { key: "index", sortable: false, title: "Action" },
  { key: "evaluation", sortable: false, title: "Evaluation" },
]);
const studentHeaders = ref([
  { key: "originalName", sortable: false, title: "File Name" },
  { key: "createdAt", sortable: true, title: "Submission Date" },
  { key: "sType", sortable: true, title: "Submission Type" },
  { key: "autogeneratedName", sortable: false, title: "File" },
]);
const apiUrl = import.meta.env.VITE_API_URL;

// Functions

onMounted(async () => {
  try {
    const token = localStorage.getItem("access_token");
    const response = await axios.get(`${apiUrl}/lecturer/myfiles`, {
      headers: { Authorization: token },
    });
    filesSubmission.value = response.data.map((file) => ({
      ...file,
      createdAt: formatDate(file.createdAt),
      sType: separateName(file.sType),
    }));
    aggregateStudents();
  } catch (error) {
    console.error("Error fetching files:", error);
  }

  try {
    const responseCriteria = await axios.get(`${apiUrl}/api/criterias`);
    if (responseCriteria.status === 200) {
      criteriasData.value = responseCriteria.data;
    } else {
      console.error(
        "Error fetching evaluation criteria:",
        responseCriteria.data
      );
    }
  } catch (error) {
    console.error("Error fetching evaluation criteria:", error);
  }
});

const aggregateStudents = () => {
  const studentsMap = {};
  filesSubmission.value.forEach((file) => {
    if (!studentsMap[file.studentId]) {
      studentsMap[file.studentId] = {
        studentId: file.studentId,
        studentName: file.studentName,
        MatricNumber: file.MatricNumber,
        studentType: file.studentType,
        createdAt: file.createdAt,
        program: file.program,
        submissions: [],
      };
    }
    studentsMap[file.studentId].submissions.push(file);
  });
  students.value = Object.values(studentsMap);
};

const formatDate = (timestamp) => {
  const date = new Date(timestamp._seconds * 1000); // Convert seconds to milliseconds
  return date.toLocaleString("en-UK", {
    year: "numeric",
    day: "numeric",
    month: "numeric",
    hour: "numeric",
    minute: "numeric",
  }); // Format the date as per the locale
};

const separateName = (name) => {
  const splitName = name.split(/(?=[A-Z0-9])/);
  const newName = splitName
    .map((word) => {
      return word.charAt(0).toUpperCase() + word.slice(1);
    })
    .join(" ");

  return newName;
};

const openSubmissionsDialog = (item) => {
  item.submissionsDialog = true;
  item.evaluationDialog = false; // Close Evaluation Dialog
};

// Open Evaluation Dialog
const openEvaluationDialog = (item) => {
  studentInfo.value = {
    id: item.studentId,
    name: item.studentName,
    program: item.program,
    MatricNumber: item.MatricNumber,
  };
  item.evaluationDialog = true;
  item.submissionsDialog = false; // Close Submissions Dialog
};

// Close Dialogs
const closeDialogs = (item) => {
  item.submissionsDialog = false;
  item.evaluationDialog = false;
};
</script>

<style lang="scss" scoped>
.title {
  font-family: "DM Sans", sans-serif;
  font-weight: 400;
  font-size: 1.125rem /* 18px */;
  line-height: 1.75rem /* 28px */;
}
.titleDes {
  font-family: "Work Sans", sans-serif;
  font-size: 1rem /* 18px */;
  line-height: 1.75rem /* 28px */;
}
</style>
