<template>
  <div>
    <div class="pt-10">
      <h1 class="title text-lg font-medium">Student Proposals</h1>
      <p class="titleDes text-sm font-light">
        Here you can accept or reject student proposals
      </p>
    </div>
    <div class="w-4/5 pt-10 h-full">
      <!-- <v-expansion-panels class="mb-5 ml-1">
        <v-expansion-panel
          v-for="(proposal, index) in proposalFiles"
          :key="index"
          :elevation="4"
          class="mt-5 expantionPanel"
        >
          <template v-slot:title>
            <h1 class="title font-bold text-lg">
              {{ proposal.studentName }}
            </h1>
          </template>
          <template v-slot:text>
            <p class="commentContent text-lg pt-2">
              Proposal:
              <a
                :href="`http://localhost:8000/files/${proposal.autogeneratedName}`"
                target="_blank"
                rel="noopener noreferrer"
              >
                <span class="underline text-blue-200">
                  {{ proposal.originalName }}</span
                >
              </a>
            </p>
            <p class="commentContent text-base mt-4 font-light">
              Student ID: {{ proposal.studentId }}
            </p>
            <p class="commentContent text-base mt-4 font-light">
              Submitted At:
              {{ formatDate(proposal.createdAt) }}
            </p>
            <v-card-actions>
              <v-spacer></v-spacer>
              <v-btn color="success" variant="outlined" class="mr-2">
                Accept
              </v-btn>
              <v-btn color="error" variant="text" class="mr-2">
                Reject
              </v-btn></v-card-actions
            >
          </template>
        </v-expansion-panel>
      </v-expansion-panels> -->
      <v-card :rounded="0" :elevation="0">
        <v-text-field
          v-model="search"
          label="Search"
          prepend-inner-icon="mdi-magnify"
          single-line
          :rounded="0"
          variant="outlined"
          hide-details
        ></v-text-field>
      </v-card>
      <v-data-table :headers="headers" :items="proposalFiles" :search="search">
        <template v-slot:item.autogeneratedName="{ item }">
          <a
            :href="`http://localhost:8000/files/${item.autogeneratedName}`"
            target="_blank"
            rel="noopener noreferrer"
          >
            <span class="underline text-blue-200">
              {{ item.autogeneratedName }}</span
            >
          </a> </template
        ><template v-slot:item.index="{ item }">
          <v-btn @click="openDialog(item)" size="small" color="primary">
            Click Me
          </v-btn>
          <v-dialog v-model="item.dialog" width="800">
            <v-card title="Proposal Details">
              <v-card-text class="mt-4">
                <v-form v-model="valid">
                  <v-radio-group
                    :rules="[(v) => !!v || 'Status are required']"
                    v-model="radios"
                    inline
                  >
                    <v-radio
                      label="Accept"
                      value="accepted"
                      color="success"
                    ></v-radio>
                    <v-radio
                      class="ml-5"
                      label="Reject"
                      value="rejected"
                      color="error"
                    ></v-radio>
                  </v-radio-group>
                  <v-text-field
                    v-model="remarks"
                    label="Remarks for student"
                    :rules="[(v) => !!v || 'Remarks are required']"
                  ></v-text-field>
                </v-form>
              </v-card-text>

              <v-card-actions>
                <v-spacer></v-spacer>
                <v-btn
                  color="warning"
                  variant="outlined"
                  class="w-32"
                  text="Cancel"
                  @click="closeDialog(item)"
                ></v-btn>
                <v-btn
                  color="indigo"
                  variant="elevated"
                  class="w-32"
                  text="Submit"
                  :disabled="!valid || !radios"
                  @click="
                    submitProposalStatus(item.autogeneratedName, item.studentId)
                  "
                ></v-btn>
              </v-card-actions>
            </v-card>
          </v-dialog>
        </template>
      </v-data-table>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from "vue";
import axios from "axios";

const search = ref("");
const headers = ref([
  { key: "originalName", sortable: false, title: "File Name" },
  { key: "autogeneratedName", sortable: false, title: "File" },
  { key: "studentName", sortable: false, title: "Student" },
  { key: "createdAt", sortable: true, title: "Submission Date" },
  { key: "index", sortable: false, title: "Action" },
]);

const proposalFiles = ref([]);
const radios = ref("");
const remarks = ref("");
const valid = ref(false);

onMounted(async () => {
  const token = localStorage.getItem("access_token");
  try {
    const response = await axios.get("http://localhost:8000/getProposals", {
      headers: {
        Authorization: token,
      },
    });
    proposalFiles.value = response.data.map((proposal) => {
      return {
        ...proposal,
        createdAt: formatDate(proposal.createdAt),
      };
    });
  } catch (error) {
    console.error("Error fetching proposal files:", error);
    // Handle error
  }
});

const submitProposalStatus = async (autogeneratedName, studentId) => {
  try {
    const token = localStorage.getItem("access_token");
    const response = await axios.post(
      "http://localhost:8000/updateProposal",
      {
        autogeneratedName,
        studentId,
        newStatus: radios.value,
        newRemarks: remarks.value,
      },
      {
        headers: {
          Authorization: token,
        },
      }
    );
    if (response.status === 200) {
      console.log(response.data.message);
    }
  } catch (error) {
    console.error("Error: ", error);
  }
};

const formatDate = (timestamp) => {
  const date = new Date(timestamp._seconds * 1000); // Convert seconds to milliseconds
  return date.toLocaleString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "numeric",
    minute: "numeric",
  }); // Format the date as per the locale
};

// Function to open the dialog and set selectedItem
const openDialog = (item) => {
  item.dialog = true;
};

// Function to close the dialog and reset selectedItem
const closeDialog = (item) => {
  item.dialog = false;
  remarks.value = "";
  radios.value = "";
};
</script>

<style lang="scss" scoped>
.title {
  font-family: "DM Sans", sans-serif;
}
.titleDes {
  font-family: "Work Sans", sans-serif;
  font-size: 1rem /* 18px */;
  line-height: 1.75rem /* 28px */;
}
.commentContent {
  font-family: "Source Sans Pro", sans-serif;
}
</style>
