<template>
  <div>
    <div class="pt-10">
      <h1 class="title text-lg font-medium">Student Proposals</h1>
      <p class="titleDes text-sm font-light">
        Here you can accept or reject student proposals
      </p>
    </div>
    <div class="w-4/5 pt-10 h-full">
      <v-card :rounded="0" :elevation="0">
        <v-text-field
          v-model="search"
          label="Search"
          prepend-inner-icon="mdi-magnify"
          single-line
          :rounded="0"
          variant="outlined"
          hide-details
        ></v-text-field>
      </v-card>
      <v-data-table :headers="headers" :items="proposalFiles" :search="search">
        <template v-slot:item.autogeneratedName="{ item }">
          <a
            :href="`${apiUrl}/files/${item.autogeneratedName}`"
            target="_blank"
            rel="noopener noreferrer"
          >
            <span class="underline text-blue-800 dark:text-blue-400">
              {{ item.autogeneratedName }}</span
            >
          </a> </template
        ><template v-slot:item.index="{ item }">
          <v-btn @click="openDialog(item)" size="small" color="primary">
            Aceept/Reject
          </v-btn>
          <v-dialog v-model="item.dialog" width="800">
            <v-card title="Proposal Details">
              <v-card-text class="mt-4">
                <v-form v-model="valid">
                  <v-radio-group
                    :rules="[(v) => !!v || 'Status are required']"
                    v-model="radios"
                    inline
                  >
                    <v-radio
                      label="Accept"
                      value="accepted"
                      color="success"
                    ></v-radio>
                    <v-radio
                      class="ml-5"
                      label="Reject"
                      value="rejected"
                      color="error"
                    ></v-radio>
                  </v-radio-group>
                  <v-text-field
                    v-model="remarks"
                    label="Remarks for student"
                    :rules="[(v) => !!v || 'Remarks are required']"
                  ></v-text-field>
                </v-form>
              </v-card-text>

              <v-card-actions>
                <v-spacer></v-spacer>
                <v-btn
                  color="warning"
                  variant="outlined"
                  class="w-32"
                  text="Cancel"
                  @click="closeDialog(item)"
                ></v-btn>
                <v-btn
                  color="indigo"
                  variant="elevated"
                  class="w-32"
                  text="Submit"
                  :disabled="!valid || !radios"
                  @click="
                    submitProposalStatus(
                      item.autogeneratedName,
                      item.studentId,
                      item
                    )
                  "
                ></v-btn>
              </v-card-actions>
            </v-card>
          </v-dialog>
        </template>
      </v-data-table>
    </div>
    <v-snackbar
      :timeout="2000"
      color="indigo"
      variant="elevated"
      v-model="snackbar"
    >
      {{ responseMessage }}

      <template v-slot:actions>
        <v-btn color="white" variant="transparent" @click="snackbar = false">
          X
        </v-btn>
      </template>
    </v-snackbar>
  </div>
</template>

<script setup>
import { ref, onMounted } from "vue";
import axios from "axios";

const search = ref("");
const headers = ref([
  { key: "originalName", sortable: false, title: "File Name" },
  { key: "autogeneratedName", sortable: false, title: "File" },
  { key: "studentName", sortable: false, title: "Student" },
  { key: "createdAt", sortable: true, title: "Submission Date" },
  { key: "index", sortable: false, title: "Action" },
]);

const proposalFiles = ref([]);
const radios = ref("");
const remarks = ref("");
const valid = ref(false);
const snackbar = ref(false);
const responseMessage = ref("");
const apiUrl = import.meta.env.VITE_API_URL;

onMounted(async () => {
  const token = localStorage.getItem("access_token");
  const storedUser = JSON.parse(localStorage.getItem("user") || "{}");
  const userProgram = storedUser.coordinator_program;

  try {
    const response = await axios.get(`${apiUrl}/getProposals`, {
      headers: {
        Authorization: token,
      },
    });
    proposalFiles.value = response.data
      .filter((proposal) => proposal.studentProgram === userProgram)
      .map((proposal) => {
        return {
          ...proposal,
          createdAt: formatDate(proposal.createdAt),
        };
      });
  } catch (error) {
    console.error("Error fetching proposal files:", error);
    // Handle error
  }
});

const submitProposalStatus = async (autogeneratedName, studentId, item) => {
  try {
    const token = localStorage.getItem("access_token");
    const response = await axios.post(
      `${apiUrl}/updateProposal`,
      {
        autogeneratedName,
        studentId,
        newStatus: radios.value,
        newRemarks: remarks.value,
      },
      {
        headers: {
          Authorization: token,
        },
      }
    );
    if (response.status === 200) {
      responseMessage.value = response.data.message;
      snackbar.value = true;
      proposalFiles.value = proposalFiles.value.filter(
        (proposal) => proposal.autogeneratedName !== autogeneratedName
      );
      closeDialog(item);
    }
  } catch (error) {
    console.error("Error: ", error);
  }
};

const formatDate = (timestamp) => {
  const date = new Date(timestamp._seconds * 1000); // Convert seconds to milliseconds
  return date.toLocaleString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "numeric",
    minute: "numeric",
  }); // Format the date as per the locale
};

// Function to open the dialog and set selectedItem
const openDialog = (item) => {
  item.dialog = true;
};

// Function to close the dialog and reset selectedItem
const closeDialog = (item) => {
  item.dialog = false;
  remarks.value = "";
  radios.value = "";
};
</script>

<style lang="scss" scoped>
.title {
  font-family: "DM Sans", sans-serif;
}
.titleDes {
  font-family: "Work Sans", sans-serif;
  font-size: 1rem /* 18px */;
  line-height: 1.75rem /* 28px */;
}
.commentContent {
  font-family: "Source Sans Pro", sans-serif;
}
</style>
