<template>
  <div>
    <div class="md:w-4/5 pt-10 h-full">
      <div class="w-fit m-auto">
        <v-tabs
          class="rounded-3xl md:px-20"
          align-tabs="center"
          :bg-color="isDark ? '#fdfefb' : '#BDBDBD'"
          v-model="tabSecondry"
        >
          <v-tab value="one">Proposals</v-tab>
          <v-tab value="two">Project 1</v-tab>
          <v-tab value="three">Project 2</v-tab>
        </v-tabs>
      </div>
      <v-alert
        class="py-1 mt-4 rounded-xl"
        color="error"
        :text="errorMessage"
        icon="mdi-alert-circle"
        variant="outlined"
        v-if="errorMessage !== ''"
      ></v-alert>
      <v-card-text class="pl-0">
        <v-window disabled v-model="tabSecondry">
          <v-window-item value="one">
            <div class="pt-10">
              <h1 class="title text-lg font-medium">
                Student Proposals
                <span v-if="isLoading"
                  ><v-progress-circular
                    :size="22"
                    indeterminate
                  ></v-progress-circular
                ></span>
              </h1>
              <p class="titleDes text-sm font-light mb-4">
                Here you can accept or reject student proposals
              </p>
            </div>
            <div v-if="!isLoading && proposalFiles.length > 0">
              <v-card :rounded="0" :elevation="0">
                <v-text-field
                  v-model="search"
                  label="Search"
                  prepend-inner-icon="mdi-magnify"
                  single-line
                  :rounded="0"
                  variant="outlined"
                  hide-details
                ></v-text-field>
              </v-card>
              <v-data-table
                :headers="headersProposals"
                :items="proposalFiles"
                :search="search"
              >
                <template v-slot:item.autogeneratedName="{ item }">
                  <a
                    :href="`${apiUrl}/files/${item.autogeneratedName}`"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <span class="underline text-blue-800 dark:text-blue-400">
                      {{ item.autogeneratedName }}</span
                    >
                  </a>
                </template>
                <template v-slot:item.extra="{ item }">
                  <v-btn
                    @click="openSubmissionsDialog(item)"
                    size="small"
                    :color="
                      item.proposalsExtra.length > 0 ? 'primary' : 'black'
                    "
                    :disabled="item.proposalsExtra.length === 0"
                    text="Extra Files"
                  >
                  </v-btn>
                  <v-dialog v-model="item.submissionsDialog" width="1200">
                    <v-card title="Student Files For Project 1">
                      <v-card-text class="mt-4">
                        <v-data-table
                          class="border"
                          :headers="extrasHeaders"
                          :items="item.proposalsExtra"
                        >
                          <template v-slot:item.autogeneratedName="{ item }">
                            <a
                              :href="`${apiUrl}/files/${item.autogeneratedName}`"
                              target="_blank"
                              rel="noopener noreferrer"
                            >
                              <span class="underline text-blue-200">
                                {{ item.autogeneratedName }}</span
                              >
                            </a>
                          </template>
                        </v-data-table>
                      </v-card-text>

                      <v-card-actions>
                        <v-spacer></v-spacer>
                        <v-btn
                          color="warning"
                          variant="outlined"
                          class="w-32"
                          text="Cancel"
                          @click="closeDialogs(item)"
                        ></v-btn>
                      </v-card-actions>
                    </v-card>
                  </v-dialog>
                </template>
                <template v-slot:item.index="{ item }">
                  <v-btn @click="openDialog(item)" size="small" color="indigo">
                    Aceept/Reject
                  </v-btn>
                  <v-dialog v-model="item.dialog" width="800">
                    <v-card title="Proposal Details">
                      <v-card-text class="mt-4">
                        <v-form v-model="valid">
                          <v-radio-group
                            :rules="[(v) => !!v || 'Status are required']"
                            v-model="radios"
                            inline
                          >
                            <v-radio
                              label="Accept"
                              value="accepted"
                              color="success"
                            ></v-radio>
                            <v-radio
                              class="ml-5"
                              label="Minor Corrections"
                              value="minorCorre"
                              color="warning"
                            ></v-radio
                            ><v-radio
                              class="ml-5"
                              label="Major Corrections"
                              value="majorCorre"
                              color="warning"
                            ></v-radio
                            ><v-radio
                              class="ml-5"
                              label="Fail"
                              value="failed"
                              color="error"
                            ></v-radio>
                          </v-radio-group>
                          <v-text-field
                            v-model="remarks"
                            label="Remarks for student"
                            :rules="[(v) => !!v || 'Remarks are required']"
                          ></v-text-field>
                        </v-form>
                      </v-card-text>

                      <v-card-actions>
                        <v-spacer></v-spacer>
                        <v-btn
                          color="warning"
                          variant="outlined"
                          class="w-32"
                          text="Cancel"
                          @click="closeDialog(item)"
                        ></v-btn>
                        <v-btn
                          color="indigo"
                          variant="elevated"
                          class="w-32"
                          text="Submit"
                          :disabled="!valid || !radios"
                          @click="
                            submitProposalStatus(
                              item.autogeneratedName,
                              item.studentId,
                              item
                            )
                          "
                        ></v-btn>
                      </v-card-actions>
                    </v-card>
                  </v-dialog>
                </template>
              </v-data-table>
            </div>
            <v-skeleton-loader
              v-if="isLoading"
              class="mw-auto border"
              type="table"
            ></v-skeleton-loader>
            <v-alert
              v-if="proposalFiles.length === 0 && !isLoading"
              type="info"
              variant="outlined"
              class="my-4"
              text="No proposals were submitted yet"
            ></v-alert>
          </v-window-item>
          <v-window-item value="two">
            <h1 class="title text-lg font-medium pt-10 mb-2">
              All submissions for <strong>Project 1</strong>
              <span class="ml-2" v-if="isLoading"
                ><v-progress-circular
                  :size="22"
                  indeterminate
                ></v-progress-circular
              ></span>
            </h1>
            <div v-if="!isLoading && studentsPOne.length > 0">
              <v-card :rounded="0" :elevation="0">
                <v-text-field
                  v-model="searchP1"
                  label="Search"
                  prepend-inner-icon="mdi-magnify"
                  single-line
                  :rounded="0"
                  variant="outlined"
                  hide-details
                ></v-text-field>
              </v-card>
              <v-data-table
                class="border"
                :headers="headers"
                :items="studentsPOne"
                :search="searchP1"
              >
                <template v-slot:item.numSubmissions="{ item }">
                  {{ item.submissions.length }}
                </template>
                <template v-slot:item.index="{ item }">
                  <v-btn
                    @click="openSubmissionsDialog(item)"
                    size="small"
                    color="primary"
                  >
                    Submissions
                  </v-btn>
                  <v-dialog v-model="item.submissionsDialog" width="1200">
                    <v-card title="Student Files For Project 1">
                      <v-card-text class="mt-4">
                        <v-data-table
                          class="border"
                          :headers="studentHeaders"
                          :items="item.submissions"
                        >
                          <template v-slot:item.autogeneratedName="{ item }">
                            <a
                              :href="`${apiUrl}/files/${item.autogeneratedName}`"
                              target="_blank"
                              rel="noopener noreferrer"
                            >
                              <span class="underline text-blue-200">
                                {{ item.autogeneratedName }}</span
                              >
                            </a>
                          </template>
                        </v-data-table>
                      </v-card-text>

                      <v-card-actions>
                        <v-spacer></v-spacer>
                        <v-btn
                          color="warning"
                          variant="outlined"
                          class="w-32"
                          text="Cancel"
                          @click="closeDialogs(item)"
                        ></v-btn>
                      </v-card-actions>
                    </v-card>
                  </v-dialog>
                </template>
              </v-data-table>
            </div>
            <v-skeleton-loader
              v-if="isLoading"
              class="mw-auto border"
              type="table"
            ></v-skeleton-loader>

            <v-alert
              v-if="studentsPOne.length === 0 && !isLoading"
              type="info"
              variant="outlined"
              class="my-4"
              text="Student has not submitted any files yet for Project 1"
            ></v-alert>
          </v-window-item>
          <v-window-item value="three">
            <h1 class="title text-lg font-medium pt-10 mb-2">
              All submissions for <strong>Project 2</strong>
              <span class="ml-2" v-if="isLoading"
                ><v-progress-circular
                  :size="22"
                  indeterminate
                ></v-progress-circular
              ></span>
            </h1>
            <div v-if="!isLoading && studentsPTwo.length > 0">
              <v-card :rounded="0" :elevation="0">
                <v-text-field
                  v-model="searchP2"
                  label="Search"
                  prepend-inner-icon="mdi-magnify"
                  single-line
                  :rounded="0"
                  variant="outlined"
                  hide-details
                ></v-text-field>
              </v-card>
              <v-data-table
                class="border"
                :headers="headers"
                :items="studentsPTwo"
                :search="searchP2"
              >
                <template v-slot:item.numSubmissions="{ item }">
                  {{ item.submissions.length }}
                </template>
                <template v-slot:item.index="{ item }">
                  <v-btn
                    @click="openSubmissionsDialog(item)"
                    size="small"
                    color="primary"
                  >
                    Submissions
                  </v-btn>
                  <v-dialog v-model="item.submissionsDialog" width="1200">
                    <v-card title="Student Files For Project 2">
                      <v-card-text class="mt-4">
                        <v-data-table
                          class="border"
                          :headers="studentHeaders"
                          :items="item.submissions"
                        >
                          <template v-slot:item.autogeneratedName="{ item }">
                            <a
                              :href="`${apiUrl}/files/${item.autogeneratedName}`"
                              target="_blank"
                              rel="noopener noreferrer"
                            >
                              <span class="underline text-blue-200">
                                {{ item.autogeneratedName }}</span
                              >
                            </a>
                          </template>
                        </v-data-table>
                      </v-card-text>

                      <v-card-actions>
                        <v-spacer></v-spacer>
                        <v-btn
                          color="warning"
                          variant="outlined"
                          class="w-32"
                          text="Cancel"
                          @click="closeDialogs(item)"
                        ></v-btn>
                      </v-card-actions>
                    </v-card>
                  </v-dialog>
                </template>
              </v-data-table>
            </div>
            <v-skeleton-loader
              v-if="isLoading"
              class="mw-auto border"
              type="table"
            ></v-skeleton-loader>
            <v-alert
              v-if="studentsPTwo.length === 0 && !isLoading"
              type="info"
              variant="outlined"
              class="my-4"
              text="Student has not submitted any files yet for Project 2"
            ></v-alert> </v-window-item></v-window
      ></v-card-text>
    </div>
    <v-snackbar
      :timeout="2000"
      color="indigo"
      variant="elevated"
      v-model="snackbar"
    >
      {{ responseMessage }}

      <template v-slot:actions>
        <v-btn color="white" variant="transparent" @click="snackbar = false">
          X
        </v-btn>
      </template>
    </v-snackbar>
  </div>
</template>

<script setup>
import { ref, onMounted } from "vue";
import axios from "axios";
import { useDark } from "@vueuse/core";

const tabSecondry = ref("");
const isDark = useDark();
const search = ref("");
const headersProposals = ref([
  { key: "originalName", sortable: false, title: "File Name" },
  { key: "autogeneratedName", sortable: false, title: "File" },
  { key: "studentName", sortable: true, title: "Student" },
  { key: "studentMatricCard", sortable: true, title: "Matric No." },
  { key: "createdAt", sortable: true, title: "Submission Date" },
  { key: "extra", sortable: false, title: "Extra Files" },
  { key: "index", sortable: false, title: "Action" },
]);
const headers = ref([
  { key: "studentName", sortable: true, title: "Student Name" },
  { key: "matricCard", sortable: true, title: "Matric No." },
  {
    key: "numSubmissions",
    sortable: true,
    title: "No. of Submissions",
    align: "center",
  },
  { key: "index", sortable: false, title: "Action" },
]);
const studentHeaders = ref([
  { key: "originalName", sortable: false, title: "File Name" },
  { key: "createdAt", sortable: true, title: "Submission Date" },
  { key: "submissionType", sortable: true, title: "Submission Type" },
  { key: "autogeneratedName", sortable: false, title: "File" },
]);
const extrasHeaders = ref([
  { key: "originalName", sortable: false, title: "File Name" },
  { key: "createdAt", sortable: true, title: "Submission Date" },
  { key: "autogeneratedName", sortable: false, title: "File" },
]);

const proposalFiles = ref([]);
const radios = ref("");
const remarks = ref("");
const valid = ref(false);
const snackbar = ref(false);
const responseMessage = ref("");
const errorMessage = ref("");
const apiUrl = import.meta.env.VITE_API_URL;

const projectOneFiles = ref([]);
const projectTwoFiles = ref([]);
const studentsPOne = ref([]);
const studentsPTwo = ref([]);
const searchP1 = ref("");
const searchP2 = ref("");
const isLoading = ref(false);

onMounted(async () => {
  isLoading.value = true;
  const token = localStorage.getItem("access_token");
  const storedUser = JSON.parse(localStorage.getItem("user") || "{}");
  const userProgram = storedUser.coordinator_program;

  try {
    const response = await axios.get(`${apiUrl}/getProposals`, {
      headers: {
        Authorization: token,
      },
    });
    proposalFiles.value = response.data
      .filter((proposal) => proposal.studentProgram === userProgram)
      .map((proposal) => {
        if (proposal.proposalsExtra && proposal.proposalsExtra.length > 0) {
          proposal.proposalsExtra = proposal.proposalsExtra.map((extra) => {
            return {
              ...extra,
              createdAt: formatDate(extra.createdAt),
            };
          });
        }
        return {
          ...proposal,
          createdAt: formatDate(proposal.createdAt),
        };
      });
  } catch (error) {
    console.error("Error fetching proposal files:", error);
    if (error.response && error.response.status === 500) {
      errorMessage.value = error.response.data.error;
    }
    errorMessage.value = "An error occurred while fetching proposal files.";
  }
  try {
    // Fetch submissions /api/coordSubmissions
    const response = await axios.get(`${apiUrl}/api/coordSubmissions`, {
      headers: {
        Authorization: token,
      },
    });
    if (response.status === 200) {
      projectOneFiles.value = response.data
        .filter((submission) => submission.projectType === "pOne")
        .map((submission) => {
          return {
            ...submission,
            createdAt: formatDate(submission.createdAt),
            submissionType: separateName(submission.submissionType),
          };
        });
      aggregateStudents(projectOneFiles, studentsPOne);
      projectTwoFiles.value = response.data
        .filter((submission) => submission.projectType === "pTwo")
        .map((submission) => {
          return {
            ...submission,
            createdAt: formatDate(submission.createdAt),
            submissionType: separateName(submission.submissionType),
          };
        });
      aggregateStudents(projectTwoFiles, studentsPTwo);
    }
  } catch (error) {
    if (error.response && error.response.status === 500) {
      errorMessage.value = error.response.data.error;
    }
    errorMessage.value = "An error occurred while fetching submissions.";
  }
  isLoading.value = false;
});

const submitProposalStatus = async (autogeneratedName, studentId, item) => {
  try {
    const token = localStorage.getItem("access_token");
    const response = await axios.post(
      `${apiUrl}/updateProposal`,
      {
        autogeneratedName,
        studentId,
        newStatus: radios.value,
        newRemarks: remarks.value,
      },
      {
        headers: {
          Authorization: token,
        },
      }
    );
    if (response.status === 200) {
      responseMessage.value = response.data.message;
      snackbar.value = true;
      proposalFiles.value = proposalFiles.value.filter(
        (proposal) => proposal.autogeneratedName !== autogeneratedName
      );
      closeDialog(item);
    }
  } catch (error) {
    console.error("Error: ", error);
  }
};

const formatDate = (timestamp) => {
  const date = new Date(timestamp._seconds * 1000); // Convert seconds to milliseconds
  return date.toLocaleString("en-UK", {
    year: "numeric",
    month: "numeric",
    day: "numeric",
    hour: "numeric",
    minute: "numeric",
    hour12: true,
  });
};

// Function to open the dialog and set selectedItem
const openDialog = (item) => {
  item.dialog = true;
};

// Function to close the dialog and reset selectedItem
const closeDialog = (item) => {
  item.dialog = false;
  remarks.value = "";
  radios.value = "";
};

const aggregateStudents = (type, student) => {
  const studentsMap = {};
  type.value.forEach((file) => {
    if (!studentsMap[file.studentId]) {
      studentsMap[file.studentId] = {
        studentId: file.studentId,
        studentName: file.studentName,
        matricCard: file.matricCard,
        submissions: [],
      };
    }
    studentsMap[file.studentId].submissions.push(file);
  });
  student.value = Object.values(studentsMap);
};

const separateName = (name) => {
  const splitName = name.split(/(?=[A-Z0-9])/);
  const newName = splitName
    .map((word) => {
      return word.charAt(0).toUpperCase() + word.slice(1);
    })
    .join(" ");

  return newName;
};

const openSubmissionsDialog = (item) => {
  item.submissionsDialog = true;
};

// Close Dialogs
const closeDialogs = (item) => {
  item.submissionsDialog = false;
};
</script>

<style lang="scss" scoped>
.title {
  font-family: "DM Sans", sans-serif;
}
.titleDes {
  font-family: "Work Sans", sans-serif;
  font-size: 1rem /* 18px */;
  line-height: 1.75rem /* 28px */;
}
.commentContent {
  font-family: "Source Sans Pro", sans-serif;
}
</style>
